### ISSUE TITLE
Try to understand what is the argument "collection"

### ISSUE THREAD

**Issue by Spamme1** [nightroman/Mdbc#10]
I'm try to understand what should I pass for the argument "collection", but I can't find anywhere an example.
I was trying to use a string but it doesn't work:
```
PS C:\Users\vagrant\Desktop> Get-MdbcData -Collection Test
Get-MdbcData : Cannot bind parameter 'Collection' to the target. Exception setting "Collection": "Unexpected type of parameter or variable Collection."
At line:1 char:26
+ Get-MdbcData -Collection Test
+                          ~~~~
    + CategoryInfo          : WriteError: (:) [Get-MdbcData], ParameterBindingException
    + FullyQualifiedErrorId : ParameterBindingFailed,Mdbc.Commands.GetDataCommand
```

**Comment by nightroman** [comment]
Take a look at

```powershell
    Get-Help Get-MdbcData -Full
```

i.e. for the parameter `Collection`

    -Collection
        Collection object. It is obtained by Connect-Mdbc, Open-MdbcFile, or
        using the driver methods, for example from a database instance. If it
        is not specified then the variable Collection is used.

It looks like you are trying to pass the collection name. Instead, you should
pass the collection instance, i.e. the variable. In most cases, this variable
is `$Collection`, created by `Connect-Mdbc and` it should not be even specified,
it is assumed by default.

Example with all defaults:

```powershell
    # this creates the variable $Collection for you
    Connect-Mdbc <connection-string> MyDatabase MyCollection
    
    # it uses $Collection by default
    Get-MdbcData
```

Example with custom variables:

```powershell
    # now we tell the variable name for the collection - $MyColl
    Connect-Mdbc <connection-string> MyDatabase MyCollection -CollectionVariable MyColl
    
    # now we have to specify $MyColl
    Get-MdbcData -Collection $MyColl
```

**Comment by Spamme1** [comment]
So if I have two or more collections in my database I have always to create a new "connection" every time that I need to get data from the other collection?
```
#Need some data from the first collection
Connect-Mdbc . Test -CollectionName FirstCollection
Get-MdbcData
#Need some data from the second collection, uh I have to create a second connection because the collection is an array of all collections? So how can I choose from which collection I want to get the data?
Connect-Mdbc . Test -CollectionName SecondCollection
Get-MdbcData
#Need some data from the first collection, uh I have to create again the connection, this is quite annoying
Connect-Mdbc . Test -CollectionName FirstCollection
Get-MdbcData
```

**Comment by nightroman** [comment]
You are using the first example from my answer.
It is designed for simple scenarios with one collection.

Now let's take a look at my second *Example with custom variables*.
It is designed for scenarios with several collections.
In your case it will look like:

```powershell
    #Connect two collections, specify variables for using them later
    Connect-Mdbc . Test -CollectionName FirstCollection -CollectionVariable FirstCollection
    Connect-Mdbc . Test -CollectionName SecondCollection -CollectionVariable SecondCollection

    #Need some data from the first collection
    Get-MdbcData -Collection $FirstCollection

    #Need some data from the second collection
    Get-MdbcData -Collection $SecondCollection

    #Need some data from the first collection
    Get-MdbcData -Collection $FirstCollection

    #Need some data from the second collection
    Get-MdbcData -Collection $SecondCollection
```

> #Need some data from the first collection, uh I have to create again the connection, this is quite annoying

You do not have to create the connections again, use `$FirstCollection` and `$SecondCollection`
in `Get-MdbcData` as many times as needed.
