### ISSUE TITLE
Weird issue connecting 

### ISSUE THREAD

**Issue by sunitjoshi** [nightroman/Mdbc#11]
I'm having a weird issue when trying to connect to db/collection.
 If I do this from PS prompt it works:
`Connect-Mdbc . "Xamain" "Students"`

Then call this function and it works:

```
function List-XamarinUniv
{
	[CmdletBinding()]
    param
	(
		[Parameter(Mandatory=$false)]
		[string]$mgrEmail="."
	)
	#Connect-XamarinUniv
	$query = New-MdbcQuery MgrEmail -Matches $mgrEmail, 'i'
	Get-MdbcData -Query $query -AS PS -SortBy MgrEmail | Select MgrEmail, UserEmails, _Id
}
```

If I try  to connect via a function (below) & uncomment its call above, List-XamarinUniv fails:

function Connect-XamarinUniv
```
{
	#Default collection is Xamarin
	$db="Xamarin"
	$coll="Students"
	Connect-Mdbc . $db $coll
}
#This fails
List-XamarinUnivStudents
```

Error:
> Get-MdbcData : Specify a collection by the parameter or variable Collection.

rgds
SJ

**Comment by nightroman** [comment]
What does "#This fails" mean? Could you please provide the error message?

What is `List-XamarinUniStudents`? It is not defined in the code you provided.

Could you please edit your message to improve code formatting? You triple backticks instead of singles in order to wrap multi-line code.

**Comment by sunitjoshi** [comment]
I've updated it. 

Rgds
EA

**Comment by nightroman** [comment]
You have to call `Connect-XamarinUniv` with `.` operator

```powershell
. Connect-XamarinUniv
```

Read the help. `Get-MdbcData` by default requires the variable `$collection`. It is created for you by `Connect-Mdbc` **in the scope where it is called**. Thus, in your scenario, you should call `Connect-XamarinUniv` in the current scope, i.e. by the operator `.`.

There are other ways of doing the same. But it is still RTFM + regular PowerShell.

**Comment by sunitjoshi** [comment]
Ok, I was looking at this:
```Connect-Mdbc [[-ConnectionString] <String>] [[-DatabaseName] <String>] [[-CollectionName] <String>]```

And used the Database and Collection names...

**Comment by sunitjoshi** [comment]
Thanks! `. Connect-XamarinUni` call works!
