### ISSUE TITLE
Powershell Core Support 

### ISSUE THREAD

**Issue by r2690698** [nightroman/Mdbc#12]
module does not work on .net core ( and thus mac and linux).

**Comment by nightroman** [comment]
Thank you. What are the symptoms?

I wonder if the old C# driver supposed to work on .NET core.

**Comment by nightroman** [comment]
The existing version was not supposed to work on core.
The new version 5.0.0 is released with C# driver 2.4.4.
In theory, it should work on core *supported* by the driver.
