### ISSUE TITLE
<= Support in Invoke-MdbcAggregate

### ISSUE THREAD

**Issue by ChaosRocket** [nightroman/Mdbc#13]
I need to search for document field "population" <= 500000 in ....

$AllSystems=Invoke-MdbcAggregate @(
    @{ '$match' = @{
    }}
    @{ '$sort' = @{name = 1} }
    @{ '$lookup' = @{
        'from' = 'stations'
        'localField' = 'id'
        'foreignField' = 'system_id'
        'as' = 'stations'
    }}
) -Collection $systems

Is this possible ?

**Comment by nightroman** [comment]
TBH, I do not know. I am not an expert in MongoDB. Mdbc just provides some PowerShell helpers. `Invoke-MdbcAggregate` is one of the helpers, rather pretty low level. Have you tried yourself the above code?

**Comment by ChaosRocket** [comment]
$AllSystems=Invoke-MdbcAggregate @(
    @{ '$match' = @{
        name = 'Neto'
    }}
    @{ '$sort' = @{name = 1} }
    @{ '$lookup' = @{
        'from' = 'stations'
        'localField' = 'id'
        'foreignField' = 'system_id'
        'as' = 'stations'
    }}
) -Collection $systems

Works Name ="Neto" matches

But I cant work out how to do <= or >= for int32 number match

**Comment by nightroman** [comment]
I think you should learn the aggregation pipeline, the operator `$match` in the first place:
https://docs.mongodb.com/manual/reference/operator/aggregation/match/#pipe._S_match

Here is one of the examples from there:

```jscript
db.articles.aggregate( [
  { $match: { $or: [ { score: { $gt: 70, $lt: 90 } }, { views: { $gte: 1000 } } ] } },
  { $group: { _id: null, count: { $sum: 1 } } }
] );
```
Note `$gt`, `$lt`, `$gte` operators.

**Comment by ChaosRocket** [comment]
yep thats what I am saying I can do In mongo .js query, cant seem to translate it into POSH

**Comment by nightroman** [comment]
Translating json into a hashtable should be rather straightforward.

What is your working json and what is the hashtable you get as a result? Perhaps I will help to figure out the mistake.

**Comment by ChaosRocket** [comment]
So got it working... another example in the module showing a) numbers and b) multiple checks would be nice.  Thanks for help. 

$AllSystems=Invoke-MdbcAggregate @(
    @{ '$match' = @{
        population = @{ '$lte' = 25000000000} #25000000000
        is_populated = 1
    }}
    @{ '$sort' = @{population = -1} }
    @{ '$lookup' = @{
        'from' = 'stations'
        'localField' = 'id'
        'foreignField' = 'system_id'
        'as' = 'stations'
    }}
) -Collection $systems
$AllSystems.count

**Comment by nightroman** [comment]
> another example in the module showing a) numbers and b) multiple checks would be nice.

Probably. At the same time, we assume Mdbc users know MongoDB or know how to find answers in MongoDB manuals. In Mdbc, we document its API on top of the C# driver, not the driver itself or MongoDB.

**Comment by ChaosRocket** [comment]
Yes, its the .js -> posh conversation I am having trouble with.  truely surperb  posh module !
