### ISSUE TITLE
how to add pester result using Add-MdbcData?

### ISSUE THREAD

**Issue by simonfangyingzhang** [nightroman/Mdbc#14]
Hi Guru,

I want to save my test result using Pester to MongoDB, 

looks like Add-MdbcData only accepts a dictionary, but test result using Pester something like 2-level PSCustomerOBject objects, how should I convert it to use Add-MdbcData?

thanks

**Comment by simonfangyingzhang** [comment]
https://stackoverflow.com/questions/40495248/powershell-hashtable-from-json resolved my problem, thanks

**Comment by nightroman** [comment]
I am glad you found a way to do this. But I am still interested in the details. Why did not it work exactly? In theory, Mdbc should convert PSObject's to BSON itself.

**Comment by simonfangyingzhang** [comment]
$result is returned from Pester, but $result|add-mdbcdata failed, let me know if need more info, thanks

PS C:\WINDOWS\system32> $result


TagFilter         : {}
ExcludeTagFilter  : {}
TestNameFilter    :
TotalCount        : 2
PassedCount       : 1
FailedCount       : 1
SkippedCount      : 0
PendingCount      : 0
InconclusiveCount : 0
Time              : 00:00:00.3266626
TestResult        : {@{ErrorRecord=; ParameterizedSuiteName=; Describe=Notepad; Parameters=System.Collections.Specialized.OrderedDictionary; Passed=True; Show=All; FailureMessage=; Time=00:00:00.2947451; Name=Exists in
                    Windows folder; Result=Passed; Context=; StackTrace=}, @{ErrorRecord=Expected: {false}
                    But was:  {True}; ParameterizedSuiteName=; Describe=Notepad; Parameters=System.Collections.Specialized.OrderedDictionary; Passed=False; Show=All; FailureMessage=Expected: {false}
                    But was:  {True}; Time=00:00:00.0319175; Name=Exists in Linux folder; Result=Failed; Context=; StackTrace=at <ScriptBlock>, C:\PowerCLIinAutomationTesting\Pester.Tests.ps1: line 27
                    27:                 $Type -eq "pvscsi"|should be false}}



PS C:\WINDOWS\system32> $result|Add-MdbcData
Add-MdbcData : .NET type System.TimeSpan cannot be mapped to a BsonValue.
At line:1 char:9
+ $result|Add-MdbcData
+         ~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (@{TagFilter=Sys...ystem.Object[]}:PSObject) [Add-MdbcData], ArgumentException
    + FullyQualifiedErrorId : BsonValue,Mdbc.Commands.AddDataCommand

PS C:\WINDOWS\system32>

**Comment by nightroman** [comment]
> Add-MdbcData : .NET type System.TimeSpan cannot be mapped to a BsonValue.

That is the reason. No, I do not need more info. All looks fine, by design, because not everything can be automatically converted to BSON.
