### ISSUE TITLE
Create unique index

### ISSUE THREAD

**Issue by enterprisemike** [nightroman/Mdbc#15]
Hi,

This set of cmdlets is great! Thank you for writing them.

Could you please help me find information on how to create a unique index using the $Collection.CreateIndex() method? I've found doco that describes the interfaces, but I haven't found any examples to help me understand how to use the overload:
MongoDB.Driver.WriteConcernResult CreateIndex(MongoDB.Driver.IMongoIndexKeys keys, MongoDB.Driver.IMongoIndexOptions options)

It seems that every time I try to specify the unique param it reads it as a field name, so my index isn't unique:
**PS> $collection.CreateIndex('{ "tax-id": 1 }', '{ unique: true }')
PS> $Collection.GetIndexes()
DroppedDups  : False
IsBackground : False
IsSparse     : False
IsUnique     : False
Key          : {{ "tax-id": 1 }=1, { unique: true }=1}
Name         : {_"tax-id":_1_}_1_{_unique:_true_}_1
Namespace    : WalkForward.test
RawDocument  : {v=1, key={ "{ \"tax-id\": 1 }" : 1, "{ unique: true }" : 1 }, name={_"tax-id":_1_}_1_{_unique:_true_}_1, ns=WalkForward.test}
TimeToLive   : 10675199.02:48:05.4775807
Version      : 1**

Thank you for your help!

Mike

**Comment by nightroman** [comment]
This is rather a question about the .NET driver than Mdbc. It's all right but
it may be better to use the .NET driver manuals or forums for further details.
Mdbc does not provide wrappers/helpers for all .NET driver features.

As far as I understand, you should use `CreateIndex` with keys and options (as
you are trying). Keys and options should be created using so called builders.

Sample

```powershell
Connect-Mdbc
$null = $Collection.DropAllIndexes()

$keys = (New-Object MongoDB.Driver.Builders.IndexKeysBuilder).Ascending('tax-id')
$options = (New-Object MongoDB.Driver.Builders.IndexOptionsBuilder).SetName('tax-id').SetUnique($true)
$Collection.CreateIndex($keys, $options)

$Collection.GetIndexes()
```

Output

```
DroppedDups  : False
IsBackground : False
IsSparse     : False
IsUnique     : False
Key          : {_id=1}
Name         : _id_
Namespace    : test.test
RawDocument  : {v=2, key={ "_id" : 1 }, name=_id_, ns=test.test}
TimeToLive   : 10675199.02:48:05.4775807
Version      : 2

DroppedDups  : False
IsBackground : False
IsSparse     : False
IsUnique     : True
Key          : {tax-id=1}
Name         : tax-id
Namespace    : test.test
RawDocument  : {v=2, unique=true, key={ "tax-id" : 1 }, name=tax-id...}
TimeToLive   : 10675199.02:48:05.4775807
Version      : 2
```

**Comment by enterprisemike** [comment]
Hi Roman,

Thank you so much, that is exactly what I needed. 

Mike

**Comment by nightroman** [comment]
Hi Mike, I am glad to hear this. I will add this sample to a new *HowTo.test.ps1* in the next push.

**Comment by enterprisemike** [comment]
Great idea, I looked through the test scripts but I had trouble working out how the builders should be used. (I always find the  MS doco pretty unhelpful).

Your example showed me clearly.

Thanks again.

Mike
