### ISSUE TITLE
Get-MdbcData : SubType must be UuidStandard, not UuidLegacy, when GuidRepresentation is Unspecified.

### ISSUE THREAD

**Issue by Spamme1** [nightroman/Mdbc#16]
I found only something in the release notes: https://github.com/nightroman/Mdbc/blob/master/Release-Notes.md
But it is only mentioned that the environment variable Mdbc_GuidRepresentation should be set to CSharpLegacy, but I didn't found anywhere how to set it.

I tried this one: $Env:Mdbc_GuidRepresentation=$GuidRepresentation::CSharpLegacy, but it didn't work.

**Comment by nightroman** [comment]
(1) Please try instead this

```powershell
$Env:Mdbc_GuidRepresentation = 'CSharpLegacy'
```

This should be done before importing the module, or at least before using it.

(2) I am not sure what the issue title means.

**Comment by nightroman** [comment]
Alternatively,

```powershell
# ensure the .NET driver types are imported
Import-Module Mdbc

# at any point, change the default .NET GuidRepresentation to the required
[MongoDB.Bson.BsonDefaults]::GuidRepresentation = [MongoDB.Bson.GuidRepresentation]::CSharpLegacy
```

Thus, you do not have to use the environment variable. But it is convenient in
some cases. For example you can just can it globally and permanently for a
machine.

If the issue is not resolved please reopen with some more details.
