### ISSUE TITLE
Proper Syntax for Find

### ISSUE THREAD

**Issue by xyker** [nightroman/Mdbc#17]
I'm trying to figure out what the proper syntax is for finding an object that has an array with another object_id.  A simplified version of my data looks like this:
```
$system_collection
{_id: 1, name: 'abc', hosts: {'host1', 'host2', 'host3'} }
{_id: 2, name: 'xyz', hosts: {'host1', 'host3'} }
{_id: 3, name: 'qwe', hosts: {'host2'} }
```

I'm trying to query for all the rows that have a certain host in the array of hosts.

Here's what I've tried so far:

`Get-Mdbcdata (New-MdbcQuery _id -In @{hosts = @{'$in' = @('host2')}}) -Collection $system_collection
`
I'm convinced my syntax is off.  Thanks!

**Comment by nightroman** [comment]
I think you need `-All`, not `-In`. (Did you read `help -full New-MdbcQuery`?).
Something like `New-MdbcQuery hosts -All host2`

**Comment by xyker** [comment]
Perfect!  Thanks!
