### ISSUE TITLE
cant deal boolean

### ISSUE THREAD

**Issue by kanxue660** [nightroman/Mdbc#18]
for example, is_deal type is boolean,the code output is null
`
$data=Get-MdbcData (New-MdbcQuery is_deal -EQ False)
$data._id
`

**Comment by nightroman** [comment]
It's a frequent *PowerShell* mistake.
You should use the Boolean value `$false` instead of the string value `False`.

```powershell
$data=Get-MdbcData (New-MdbcQuery is_deal -EQ $false) $data._id
```
