### ISSUE TITLE
ssl and x509 authentication question

### ISSUE THREAD

**Issue by Drew40B** [nightroman/Mdbc#21]
Hello,
   Is it possible to specify a CA certificate to use for SSL? Similarly we will be using x509 for authentication and authorization. How can I specify what user certificate to use?

**Comment by nightroman** [comment]
Hello, sorry for the delay.
I do not know much about this area. What cmdlet are you talking about? Is this possible by C# driver API?

**Comment by nightroman** [comment]
Closing for now. Feel free to open with some more details.
