### ISSUE TITLE
Scoping issues

### ISSUE THREAD

**Issue by Stephanevg** [nightroman/Mdbc#23]
Hi @nightroman 
I have been using your module the whole day, pretty cool stuff! 👍 

I do have a small issue, which is pretty annoying, and make your module, not usable in our use case:

I do have a pretty complex logging module, which writes data to different sources using PowerShell classes.
I have the (kind of) the following code (I have over simplified it,as I do have a way bigger construct, but this actually highlights the root issue I think:

```powershell

Class MonGoDBScopeTest{

    ConnectDB(){
        import-module mdbc -force
        Connect-Mdbc -ConnectionString . -DatabaseName log -CollectionName test -ErrorAction Stop
    }
}

Class Logger {
    write([HashTable]$Message){
    $Message | Add-MdbcData
    }
}

Function WriteLog {
    Param(
        [String]$Message,
        [String]$Type
    )
  $Logger = [Logger]::New()  
  $Hash = @{}
  $Hash.Message = $Message
  $Hash.Type = $Type
  $Logger.write($Hash)
}


# main script 
in script
$MonGo = [MonGoDBScopeTest]::new()
$MonGo.ConnectDB()

WriteLog -Message "Woop" -Type error
```

(Also, normally all my functions and classes are in a module (psm1) file.)

When I launch the above code, I do have the following error:

``` powershell
[A][1] C:\Windows\system32 >
👍>  C:\Users\Code\PowerShell\__Builds\LogginBuilds.ps1
Add-MdbcData : Specify a collection by the parameter or variable Collection.
At C:\Users\Code\PowerShell\__Builds\LogginBuilds.ps1:24 char:16
+     $Message | Add-MdbcData
+                ~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (System.Collections.Hashtable:PSObject) [Add-MdbcData], PSArgumentException
    + FullyQualifiedErrorId : BsonValue,Mdbc.Commands.AddDataCommand
```

I have the impression that the issue resived in the scope from the $Server variable
 I tried to higher it up like this

```powershell
Connect-Mdbc -ConnectionString . -DatabaseName log -CollectionName mycollection -NewCollection -ErrorAction Stop -ServerVariable $Global:Server
```
But it didn't work

Any suggestion? on how to make this construct work?

**Comment by nightroman** [comment]
- Way 1. `ConnectDB()` should return the objects that will be used after its call.
- Way 2. `ConnectDB()` should assign them as properties of the class, say, `<connect>; $this.Collection = $Collection`. Then after `$MonGo.ConnectDB()` the caller may use `$MonGo.Collection` for next commands.

**Comment by nightroman** [comment]
There are mo ways, it's all up to you, the author. This is not about Mdbc, as such, it's about programming in PowerShell.

For example, make `ConnectDB` a function and call it *dot-sourced*. Then it will create the required `$Collection` variable in the calling scope. This variable will be available for the next call of logger, no changes are needed.

**Comment by Stephanevg** [comment]
Hi, thanks for your fast reponse.

Se here my responses:

## Way 1
`
Way 1. ConnectDB() should return the objects that will be used after its call.
`
That would be an absolute good way to handle this, I agree. But if you look at the code inside the method, the only thing I am doing, is calling the `Connect-Mdbc` which doesn't return anything.
Is it possible to make him return the connection created?


## Way 2

`
Way 2. ConnectDB() should assign them as properties of the class, say, <connect>; $this.Collection = $Collection. Then after $MonGo.ConnectDB() the caller may use $MonGo.Collection for next commands.
`

That is what I would have normaly done. (for SQL for instance, that is how I did it). BUT, then the problem is 'shifted' to `$Message | Add-MdbcData`. How can I make sure that `Add-MdbcData` will be able to find the right connection? (I couldn't find a 'Server' or a 'connection' parameter).
That cmdlet actually expects only a variable from it's current scope, and couldn't find a way to tell him to use another one.

As I mentionned in my first message, I am hiding a lot of things, to make the problem more 'visibile'.
Changing a ConnectDB into a function and dot sourcing it, is more like a 'hack' than an actuall solution to scoping issues. To respect our global process and to keep code clean, It has to be in a method.


I hope you can help to solve this issue, that would be really awesome!

Cheers

**Comment by Stephanevg** [comment]
I also just tried like this:

```powershell
$Message | Add-MdbcData -Collection test # test is the name of my collection
```
but without success.

----------
On another note,  I added an instance variable that would keep the connection as suggested (It would be **really** nice actually if `Connect-Mdbc` could return the connection object). 



```powershell
Class MonGoDBScopeTest{
    $Connection
    ConnectDB(){
        import-module mdbc -force
        Connect-Mdbc -ConnectionString . -DatabaseName log -CollectionName test -ErrorAction Stop
        $this.Connection = Get-variable -Name server -Scope 0 -ValueOnly
    }
}
```

But then, in this scenario, how do I pass the connectionn object to your other cmdlets?

**Comment by nightroman** [comment]
> the only thing I am doing, is calling the Connect-Mdbc which doesn't return anything. Is it possible to make him return the connection created?

Yes. Please take a look at `help Connect-Mdbc -full`, namely this:

> The cmdlet connects the specified server, database, and collection and creates their reference variables in the current scope. With default names they are Server, Database, and Collection.

Thus, `$Collection` is created for you. All you need is to return it. Or assign to the property of your class.

**Comment by Stephanevg** [comment]
@nightroman Thanks, but YES, I read your help document. Either you are ignoring my problem, or I am not clear enough: From my method, I don't have access to $Collection nor $Server. They simply don't exist in that scope. 

Creating a variable in the current scope is not the same thing as returning a value ( using the `return` keyword).

And my question was: How do I pass -Collection object to the `Add-MDBCData` when the Add-MDBCData **CANNOT** find the $Collection variable?


------ 
Also, I would like to point out, that $Server and $Collection are both very common variable names, and they could very easily be overwritten in a script. Have you considered renaming them to something more MongoDB specific?

**Comment by nightroman** [comment]
> Also, I would like to point out, that $Server and $Collection are both very common variable names, and they could very easily be overwritten in a script. Have you considered renaming them to something more MongoDB specific?

If you read the help for `Connect-Mdbc` you will see that you can give these variables any names you want.

On how to pass variables to other functions using parameters, please read PowerShell help.

**Comment by nightroman** [comment]
I have got some time to take a closer look.

PowerShell classes keep surprise me (and that's why I stay away from them as
much as possible, always?). For some reason `ConnectDB` does not think variable
`$Collection` is created by `Connect-Mdbc` in its body. OK, we can do this in
an extra script block then.

Here the full working code for your scenario.

```powershell
class MonGoDBScopeTest {
    [object] ConnectDB() {
        Import-Module Mdbc -Force
        $Collection = & {
            Connect-Mdbc -ConnectionString . -DatabaseName test -CollectionName test -ErrorAction Stop
            $Collection
        }
        return $Collection
    }
}

class Logger {
    write($Collection, [HashTable]$Message) {
        $Message | Add-MdbcData -Collection $Collection
    }
}

function WriteLog {
    param(
        $Collection,
        [String]$Message,
        [String]$Type
    )
    $Logger = [Logger]::New()
    $Hash = @{}
    $Hash.Message = $Message
    $Hash.Type = $Type
    $Logger.write($Collection, $Hash)
}

# main script
$MonGo = [MonGoDBScopeTest]::new()
$Collection = $MonGo.ConnectDB()

WriteLog -Collection $Collection -Message "Woop" -Type error
```

**Comment by nightroman** [comment]
I added this PowerShell gotcha to my collection [PowerShellTraps](https://github.com/nightroman/PowerShellTraps/tree/master/Class/Method-cannot-see-created-variable)
