### ISSUE TITLE
close connection

### ISSUE THREAD

**Issue by Lichtsinnig** [nightroman/Mdbc#25]
Hi.
I have not found a method for closing a connection.
How to close the connection to the database after the request?

**Comment by nightroman** [comment]
There is no explicit Mdbc support for this. When you call `Connect-Mdbc` you get your server, database, and collection (variables) see help. Then you can call whatever the driver provides using these instances.

**Comment by nightroman** [comment]
Did you find an answer? I can see `$Server.Disconnect()` but I am not sure it is "working". `$Server` still shows `State : Connected`.

**Comment by nightroman** [comment]
From the driver docs:

> Normally there is no need to call this method so you should be sure to have a good reason to call it.

I think you do not have to care about closing anything. Why are you asking, are there any problems?

**Comment by nightroman** [comment]
Closing?

**Comment by Lichtsinnig** [comment]
Thanks for the answer!
Yes, close.
