### ISSUE TITLE
Unable to handle account administration commands

### ISSUE THREAD

**Issue by Travis0123** [nightroman/Mdbc#26]
Perhaps I'm not translating the commands but I've been trying to use Invoke-MdbcCommand to change a password.

Invoke-MdbcCommand -Command db.updateUser("myaccount",{pwd:"$NEWVAL"}) -Database $Server['admin']
Invoke-MdbcCommand : .NET type System.Management.Automation.ScriptBlock cannot be mapped to a BsonValue.

Invoke-MdbcCommand -Command @{updateUser:"myaccount",pwd:$NEWVAL} -Database $Server['admin']
Missing '=' operator after key in hash literal.

Invoke-MdbcCommand -Command @{updateUser="myaccount";pwd=$NEWVAL} -Database $Server['admin']

Command 'pwd' failed: no such command: 'pwd', bad cmd: '{ pwd: "MyNewPassWord", updateUser: "myaccount", $db: "admin" }' (response: { "operationTime" : Timestamp(1562856781, 33), "ok" : 0.0, "errmsg" : "no such command: 'pwd', bad cmd: '{ pwd: \"MyNewPassWord\", updateUser: \"myaccount\", $db: \"admin\" }'", "code" : 59, "codeName" : "CommandNotFound", "$clusterTime" : { "clusterTime" : Timestamp(1562856781, 33), "signature" : { "hash" : new BinData(0, "LVq24eoVzDIJBt0yasDnRHEBKgk="), "keyId" : NumberLong("6666514431440060417") } } })

**Comment by nightroman** [comment]
I am not an expert in this area (direct commands via `Invoke-MdbcCommand`) but, yes, it looks like you are not translating correctly. Please describe the correct command in json and we'll translate it to PowerShell hashtable together.

**Comment by Travis0123** [comment]
I know of two different methods to handle password changes.  These are the examples I've used (and references for additional background)

https://stackoverflow.com/questions/23849145/how-to-change-my-mongodb-user-password-as-non-administrator

db.runCommand(
    { updateUser: "username",
      pwd: "password"
    }
)

https://docs.mongodb.com/manual/reference/method/db.changeUserPassword/

use products
db.changeUserPassword("accountUser", "SOh3TbYhx8ypJPxmt1oOfL")

**Comment by nightroman** [comment]
```powershell
# try this
$command = @{
	updateUser = "username"
	pwd = "password"
}
Invoke-MdbcCommand -Command $command -Database ($Server['admin'])

# or one-liner
Invoke-MdbcCommand -Command @{updateUser = "username"; pwd = "password"} -Database ($Server['admin'])
```

**Comment by nightroman** [comment]
I think the order or items in the hashtable matters. So use this thrick

```powershell
Connect-Mdbc
$command = New-MdbcData
$command.updateUser = "username"
$command.pwd = "password"
Invoke-MdbcCommand -Command $command -Database ($Server['admin'])
```

or `[ordered]`

```powershell
Connect-Mdbc
$command = [ordered]@{
	updateUser = "username"
	pwd = "password"
}
Invoke-MdbcCommand -Command $command -Database ($Server['admin'])
```

**Comment by Travis0123** [comment]
Yep, that first method worked, with the New-MdbcData.
Thanks for the help!

**Comment by nightroman** [comment]
I am very glad!
Out of curiosity, what's about the second command, does it work?

**Comment by Travis0123** [comment]
Never tried it since the first one worked.  But yep, that second method looks to work as well.
