### ISSUE TITLE
Powershell Gallery

### ISSUE THREAD

**Issue by AndyHollings** [nightroman/Mdbc#27]
Please can you distribute the .Core version on PowerShell Gallery.  It would make installation much easier on clients

**Comment by nightroman** [comment]
I can. I know. But then the required PowerShell version will be 5+. I am not sure that everybody is happy with this. Maybe I am too cautious.

**Comment by AndyHollings** [comment]
There are lots of enviroments which lack the ability to install the .core varient though, for for instance it's AWS Lamda, it hard to install it but it the .Core is in PSgallery you can just add it as a required...

People are already aware of the split versions andadding "Core" to it's name will easily identify it.

I hope you will reconsider - Thanks Andy

BTW the module is only truely awesome....

**Comment by nightroman** [comment]
I am considering, do not worry. It's when, not if, hopefully quite soon.

**Comment by nightroman** [comment]
One possible way is to keep the current/legacy Mdbc package at NuGet and use the new/core one on PSGallery. `Install-Module` is for PS v5+, after all, so it makes sense.

**Comment by AndyHollings** [comment]
Yeah thats exactly what I was thinking, loving that Idea a lot... been using your stuff with the new Mongo Atlas Platform

**Comment by nightroman** [comment]
Done in v5.2.0

**Comment by AndyHollings** [comment]
Fabulous - thanks very much :D
