### ISSUE TITLE
Unable to authenticate using sasl protocol mechanism SCRAM-SHA-1

### ISSUE THREAD

**Issue by rajaschava** [nightroman/Mdbc#28]
I was trying to get the database names based on the example, however I am getting an error.

Here is my code. I created a mongo atlas API user and using those credentials.

Connect-mdbc -ConnectionString $connstring -DatabaseName test 
$global:Server = $Server
Write-Host "Server `$Server $($Server.Settings.Server)"

Returns the server details.

# Database variable
$name = @($Server.GetDatabaseNames() -like $DatabaseName)
if ($name.Count -ne 1) {
	Write-Host "Server databases: $($Server.GetDatabaseNames())"
	return
}

Here I am getting the error

Exception calling "GetDatabaseNames" with "0" argument(s): "Unable to authenticate using sasl protocol mechanism SCRAM-SHA-1."
At line:12 char:1
+ $name = @($Server.GetDatabaseNames() -like $DatabaseName)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : MongoAuthenticationException

**Comment by nightroman** [comment]
Sorry, this problem is not about Mdbc and I do not know the answer or how to help.
Try to ask/search questions at MongoDB or C# driver forums.

**Comment by rajaschava** [comment]
I figured out the error. I was using the Mongo API user details instead of database details. I made some progress but having another issue.

My requirement is to go through all the databases and search specific named collections having documents older than X date. Here is my code.

Connect-mdbc -ConnectionString $connstring 
$global:Server = $Server
$allDatabases = $Server.GetDatabaseNames()
$query = New-MdbcQuery -Name 'DateTime' -LTE '2019-09-16'

foreach($dbname in $allDatabases)
{
    $database = $Server.GetDatabase($dbname)
    $collections = $database.GetCollection('consumerstate')
    $collections.Count() #This returns the count   
    
    foreach($coll in $collections)
    {        
        Get-MdbcData -Collection $coll
        return
    }
}
Get-MdbcData is throwing the below error.
Get-MdbcData : GuidRepresentation Standard is only valid with subType UuidStandard, not with subType UuidLegacy.
Parameter name: guidRepresentation
At line:26 char:9
+         Get-MdbcData -Collection $coll

There is an overload in GetCollection method which takes MongoDB.Driver.MongoCollectionSettings but I could not create and pass this object to resolve this error. Can you please point me to some examples?

**Comment by rajaschava** [comment]
I made it work.

$settings = New-Object MongoDB.Driver.MongoCollectionSettings
$settings.GuidRepresentation = 2

foreach($dbname in $allDatabases)
{
    $database = $Server.GetDatabase($dbname)
    $collections = $database.GetCollection('consumerstate', $settings)
}
