### ISSUE TITLE
Unable to load module Connect-Mdbc

### ISSUE THREAD

**Issue by rajaschava** [nightroman/Mdbc#31]
I have installed the latest Mdbc module on 'MS windows server 2016 Datacenter'. The installation went through fine but looks like it did not download one of the required dll. When I try to call the command Connect-Mdbc, I get the below error.

connect-mdbc : The term 'connect-mdbc' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ connect-mdbc
+ ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (connect-mdbc:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

I tried to load the module manually by calling Import-Module, which is giving the exact reason for the module load failure.

Import-Module : Could not load file or assembly 'file:///C:\Program Files\WindowsPowerShell\Modules\mdbc\5.2.1\System.Runtime.InteropServices.RuntimeInformation.dll' or one of its dependencies. The system cannot find the file specified.
At line:1 char:1
+ Import-Module mdbc
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand
 
-------
Per the documentation the dll System.Runtime.InteropServices.RuntimeInformation.dll is required but the same is not found in the Mdbc script folder. I tried to install it on multiple Azure VM's with same OS and all of them have the same error. 

Am I missing something while installing?

**Comment by nightroman** [comment]
It was reported before -- https://github.com/nightroman/Mdbc/issues/30 and then closed. I would like to get to the bottom of it. What is your PowerShell version?

**Comment by nightroman** [comment]
Please show your output of `$PSVersionTable` in PS console on the target machine.

**Comment by rajaschava** [comment]
I used the below command to install the latest version of Mdbc.

Install-Module Mdbc -Scope Allusers

It also installed the nuget package manager 2.8.5.208

Here is the output of $PSVersionTable

Name                           Value                                                                                                                                                                                                                             
----                           -----                                                                                                                                                                                                                             
PSVersion                      5.1.14393.3053                                                                                                                                                                                                                    
PSEdition                      Desktop                                                                                                                                                                                                                           
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                                                           
BuildVersion                   10.0.14393.3053                                                                                                                                                                                                                   
CLRVersion                     4.0.30319.42000                                                                                                                                                                                                                   
WSManStackVersion              3.0                                                                                                                                                                                                                               
PSRemotingProtocolVersion      2.3                                                                                                                                                                                                                               
SerializationVersion           1.1.0.1

**Comment by rajaschava** [comment]
Here is the output: 394802

I also tried to install the package using nuget. Still no luck.

Install-Package Mdbc -Force -Confirm

**Comment by nightroman** [comment]
According to this [SO answer](https://stackoverflow.com/a/55094656/323582) the minimum required .NET Framework version is 4.7.1.

Your system/.NET is older, `Version` 394802 means .NET Framework 4.6.2, see [How to: Determine which .NET Framework versions are installed](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md).

The latest Mdbc package on PSGallery is built for PS Core and PS 5.??. This is
documented but I did not realise the new requirements, either newer PS is
needed (I have PSVersion=5.1.17763.592) or at least .NET 4.7.1 should be
installed.

How to solve your problem. Either upgrade your machine (PS and probably .NET)
or use the package from NuGet which is still built for PS v3-5. Unfortunately
this package is installed manually, see README.

Sorry for inconveniences but Mdbc moves forward and counts on newer setup's.
The old way is still provided... See this discussion -- https://github.com/nightroman/Mdbc/issues/27

**Comment by nightroman** [comment]
> Install-Package Mdbc -Force -Confirm

I do not know what this command does. Probably it is not installing the module in the PowerShell way. See README and follow the described steps for the legacy package from NuGet.

**Comment by nightroman** [comment]
I have updated [README](https://github.com/nightroman/Mdbc/blob/master/README.md) in the repository, namely mentioned the minimum required .NET version 4.7.1 for the PSGallery package.

**Comment by rajaschava** [comment]
Ok, thank you. I have upgraded my .net framework to 4.7.2 and restarted the VM. Even after restart I got the same error for Connect-Mdbc. However when I imported the module manually, I was able to use the mdbc commands. Not sure why it is not automatically loaded.

**Comment by nightroman** [comment]
> Install-Package Mdbc -Force -Confirm

I think it just downloaded the package to `C:\Program Files\PackageManagement\NuGet\Packages`. This is not the same as installing the module. Remove it or move/install the `tools` to one of PSModule locations as `Mdbc`.

**Comment by nightroman** [comment]
>  However when I imported the module manually, I was able to use the mdbc commands. Not sure why it is not automatically loaded.

PowerShell auto module discovery may not always work as one expect especially in older PS versions (like yours).

Closing?

**Comment by rajaschava** [comment]
Sure, thank you for your quick response.
