### ISSUE TITLE
Update-MdbcData : Cannot bind parameter 'Update' to the target. 

### ISSUE THREAD

**Issue by mgeorgebrown89** [nightroman/Mdbc#32]
I set the data with a PSObject just fine, like so:

    @{_id = $ManifestEntry.ReleaseNumber; Value = $ManifestEntry } | Add-MdbcData

Then when I go to update it:

    Update-MdbcData @{_id = $manifestEntry.releaseNumber }  @{'$set' = @{value = 
    $manifestEntry } }

It gives me this error:

`Update-MdbcData : Cannot bind parameter 'Update' to the target. Exception setting "Update": ".NET type System.Management.Automation.PSObject cannot be mapped to a BsonValue."`

Am I missing something here? or is the Update-MdbcData cmdet not ready?

I'm really liking what I see so far. It's been very helpful!

**Comment by nightroman** [comment]
@mgeorgebrown89 Thank you for reporting this. Yes, there is a recent bug, the fix is coming.

Regardless, mind case sensitive names. In the examples, on adding data you are using `Value =`, on updating `value =`. In PowerShell they are the same but in Mdbc and driver they are different.

**Comment by nightroman** [comment]
Fixed in v6.0.2
