### ISSUE TITLE
Version 6.3.0 does not work with Azure CosmosDB

### ISSUE THREAD

**Issue by petrepopescu21** [nightroman/Mdbc#33]
Using Azure CosmosDB with the MongoDB API and running Get-MdbcData -Count -Filter {...} throws an error:
`Get-MdbcData : Sessions are not supported by this version of the server.`

6.2.0 works fine with the same piece of code.
For Connect-Mdbc, the TLS-enabled connection string was used.

**Comment by nightroman** [comment]
Thank you for the report and sorry for the inconvenience. I do not have a good solution right away but I am working on this.

Mdbc should use implicit sessions like the driver does internally. This API is not public though. I'll ask C# driver developers for the options.

**Comment by nightroman** [comment]
Could you please test some workaround attached?
[_191204_184720_Mdbc.zip](https://github.com/nightroman/Mdbc/files/3923456/_191204_184720_Mdbc.zip)

**Comment by nightroman** [comment]
Please try v6.3.1 and let me know if the workaround works.
