### ISSUE TITLE
Latest version does not support New-MdbcQuery

### ISSUE THREAD

**Issue by n0tspam** [nightroman/Mdbc#34]
I had a script that allowed me to query my database with that command. I noticed it is no longer working, is this part of the latest update? If so, what is the workaround?

**Comment by nightroman** [comment]
Yes, this cmdlet was removed in v6.0.0, see https://github.com/nightroman/Mdbc/blob/master/Release-Notes.md#v600

Compose filters (queries) as JSON, exactly as MongoDB manuals describe, or similar PowerShell hashtable expressions.
