### ISSUE TITLE
How to update an entry using Update-mdbcData

### ISSUE THREAD

**Issue by n0tspam** [nightroman/Mdbc#35]
I am trying to update the IP Address of an entry in my database. Since the deprecation of the older functions, I am trying `Update-MdbcData -filter '{"":""}' -update '{"IP":"test"}` but it is returning an error telling me my "IP" element is not valid, even though I have an entry with an IP Element in the database. How does this new form of updating translate from the older function New-MdbcUpdate?

**Comment by nightroman** [comment]
Assuming you want to set the field `IP`, use the operator `$set`, see [documentation](https://docs.mongodb.com/manual/reference/operator/update/set/#up._S_set).

```powershell
Update-MdbcData -filter '{"":""}' -update '{$set:{"IP":"test"}}'
```

Alternatively, use similar hashtables for filter and update expressions, they may be easier to compose in PowerShell than JSON, especially when variables are used as some values:

```powershell
$newIP = "test"
Update-MdbcData -filter @{'' = ''} -update @{'$set' = @{IP = $newIP}}
```

**Comment by n0tspam** [comment]
This worked. Thank you!
