### ISSUE TITLE
Unable to find type [MongoDB.Driver.MongoCollectionImpl`1]

### ISSUE THREAD

**Issue by avezinaATastus** [nightroman/Mdbc#36]
Hi,

I'm updating a module that uses your Module.

In my functions, I use a parameter for the target Collection, and I was typing it as `[MongoDB.Driver.MongoCollection]`. With the new version, this doesn't work anymore.

I changed the type for ``[MongoDB.Driver.MongoCollectionImpl`1[MongoDB.Bson.BsonDocument]]``, but it still doesn't work. But I think this is not the problem. If you have a better suggestion, I'm taking them.

After troubleshooting some more, I found out that all MongoDB C# driver types aren't loaded. When I try to load them with `Add-Type -TypeDefinition MongoDB.Driver`, I get this error:
```
Add-Type : c:\Users\avezina\AppData\Local\Temp\20aoxyg5.0.cs(1) : A namespace cannot directly contain members such as fields or methods

c:\Users\avezina\AppData\Local\Temp\20aoxyg5.0.cs(1) : >>> MongoDB.Driver

At line:1 char:1
+ Add-Type -TypeDefinition MongoDB.Driver
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Power...peCompilerError:AddTypeCompilerError) [Add-Type], Exception
    + FullyQualifiedErrorId : SOURCE_CODE_ERROR,Microsoft.PowerShell.Commands.AddTypeCommand
 
Add-Type : Cannot add type. Compilation errors occurred.
At line:1 char:1
+ Add-Type -TypeDefinition MongoDB.Driver
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Add-Type], InvalidOperationException
    + FullyQualifiedErrorId : COMPILER_ERRORS,Microsoft.PowerShell.Commands.AddTypeCommand
```

I do understand that the problem might be with the driver itself, but any help is appreciated

**Comment by nightroman** [comment]
In the new driver the collection type is different. And it is generic.
The actual implementation type should not be used directly, it may change.
Use the interface `[MongoDB.Driver.IMongoCollection[MongoDB.Bson.BsonDocument]]`.

Example of using it for a strongly typed function parameter:

```powershell
function Test-Collection {
    param(
        [MongoDB.Driver.IMongoCollection[MongoDB.Bson.BsonDocument]]
        $Collection
    )

    $Collection.CollectionNamespace.FullName
}

Connect-Mdbc . test test
Test-Collection $Collection
```
