### ISSUE TITLE
Connection fails when connection string contains password with business at ('@')

### ISSUE THREAD

**Issue by Insomnium** [nightroman/Mdbc#37]
Trying to connect to mongo DB using credentials with @ in password or login leads to connection string parsing failure. 
Sample code:
```ps1
Connect-Mdbc -ConnectionString "mongodb://prod_user:prod@password@prod.server:27017/classified_data_db" -DatabaseName someproddb
```
where `prod@password` is a password fails with "The connection string ... is not valid".

I believe many password policies allows and even foster using special characters, so could you please fix it?

Thanks in advance

**Comment by nightroman** [comment]
I do not know what to fix. Mdbc just calls the driver method and it fails. What else can Mdbc do?

**Comment by nightroman** [comment]
Please read https://docs.mongodb.com/manual/reference/connection-string/
namely 

> If the username or password includes the at sign @, colon :, slash /, or the percent sign % character, use percent encoding.

**Comment by Insomnium** [comment]
@nightroman , thanks for a quick reply. 
Shame on me, I didn't know about necessity of escaping. Thanks again, and of course, this issue can be closed.
