### ISSUE TITLE
 Problem with more advanced query when using Get-MdbcData, and Remove-MdbcData

### ISSUE THREAD

**Issue by joshualinde** [nightroman/Mdbc#4]
I am trying to port a JavaScript database query to PowerShell using your module.
I am able to successfully build the query object in PowerShell, but when I try to use it to find data I get errors.
It seems that it does not except an array of arguments or something like that.
Possibly I am going about this in the wrong way.

Thanks

## JavaScript: ##
```javascript
query = { blocked: { $ne: true}, $or: [
{last_seen: { $lt:(CutoffDate)}},
{last_seen: { $exists: false }, first_seen: { $lt:(CutoffDate)}}
 ]
 }
```

## Powershell: ##
```PowerShell
PS C:\Scripts>$Query = (New-MdbcQuery -Name blocked -NE $true),
                       (New-MdbcQuery -Or (New-MdbcQuery -Name last_seen -LT $CutoffDate),
                       (New-MdbcQuery -Name last_seen -NotExists),
                       (New-MdbcQuery -Name first_seen -LT $CutoffDate))

PS C:\Scripts> $Query | format-table -AutoSize
```
Name  |  Value                                                                                                                         
----  |  -----                                                                                                                         
blocked | {$ne=true}                                                                                                                    
$or  |  {last_seen={ "$lt" : NumberLong(1421098769) }, last_seen={ "$exists" : false }, first_seen={ "$lt" : NumberLong(1421098769) }}

```powershell
PS C:\Scripts>Get-MdbcData -Query $Query -Collection $Collection
```
Get-MdbcData : Cannot bind parameter 'Query' to the target. Exception setting "Query": "Can't use an array for _id."
At line:1 char:21
+ Get-MdbcData -Query $Query -Collection $Collection -Count
+                     ~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-MdbcData], ParameterBindingException
    + FullyQualifiedErrorId : ParameterBindingFailed,Mdbc.Commands.GetDataCommand

```PowerShell
PS C:\Scripts>Remove-MdbcData -Query $Query -Collection $Collection
```
Remove-MdbcData : Cannot bind parameter 'Query' to the target. Exception setting "Query": "Can't use an array for _id."
At line:1 char:36
+             Remove-MdbcData -Query $Query -Collection $Collection
+                                    ~~~~~~
    + CategoryInfo          : WriteError: (:) [Remove-MdbcData], ParameterBindingException
    + FullyQualifiedErrorId : ParameterBindingFailed,Mdbc.Commands.RemoveDataCommand

**Comment by nightroman** [comment]
I will investigate shortly. I can reproduce this.

**Comment by nightroman** [comment]
This is not a bug. The `Query` parameter does not accept arrays (meaning
implicit *And* queries). This query with explicit `New-MdbcQuery -And` works:

```
$Query = New-MdbcQuery -And (
    (New-MdbcQuery -Name blocked -NE $true),
    (New-MdbcQuery -Or (
        (New-MdbcQuery -Name last_seen -LT $CutoffDate),
        (New-MdbcQuery -Name last_seen -NotExists),
        (New-MdbcQuery -Name first_seen -LT $CutoffDate)
    ))
)
```

Your `$Query` object is an array. Do you think it would be reasonable to allow
the parameter `Query` to deal with such a case and try to convert an array of
arguments to the corresponding *And* query?

I can think of this even though, personally, I do not like this implicit *And*.

**Comment by nightroman** [comment]
Also, as far as you are converting existing JavaScript queries, i.e. not composing in Mdbc from scratch, you may find use of JSON-like hashtables as queries easier:

````
$Query = @{
	blocked = @{ '$ne' = $true}
	'$or' = @(
		@{last_seen = @{ '$lt' = $CutoffDate}}
		@{last_seen = @{ '$exists' = $false }}
		@{first_seen = @{ '$lt' = $CutoffDate}}
	)
}
````

**Comment by joshualinde** [comment]
Thank-You for your quick response! 

I will take your advice and use the JSON-Like hashtables.
You have resolve my problem. I will close this issue.
Thank-You for your advice and taking the time to answer my question.
