### ISSUE TITLE
How can I use find with case insensitivity

### ISSUE THREAD

**Issue by pressplay21** [nightroman/Mdbc#41]
Powershell variable:

$site_name = "TestSite"

Get-MdbcData @{ site_name = @{ '$regex' = [regex]"/$site_name/i" } }

The above code does not find the site name "testsite" in mongodb.

**Comment by pressplay21** [comment]
Nevermind. I figured it out.

Get-MdbcData @{site_name = @{ '$regex' = $site_name ; '$option' = 'i'} }

**Comment by nightroman** [comment]
@yvesgermain Try `$options`, see -- https://www.mongodb.com/docs/manual/reference/operator/query/regex/
