### ISSUE TITLE
FIPs compliance

### ISSUE THREAD

**Issue by jdeprato** [nightroman/Mdbc#42]
When I'm connecting using the Mdbc module functions I get an unknown error when I have FIPs enabled wherever I'm running the PowerShell script. Is this something that's been reported before? If so, is this code still being maintained where it could possibly be fixed? I noticed in the official C# driver for MongoDB FIPs compliance may have already been addressed.

**Comment by nightroman** [comment]
I have just pushed the updated Mdbc with the latest C# driver 2.10.4. Hopefully the issue was addressed there (I cannot see anything relevant in notes, though). Otherwise, I afraid, there is nothing I can do in Mdbc.
