### ISSUE TITLE
More documentation about -As needed

### ISSUE THREAD

**Issue by avezinaATastus** [nightroman/Mdbc#43]
Hi,

I'm diving again in my module that uses this one.

I'm having so much trouble wrapping my head around the output type I need.

I tried finding where I was reading my information before, but cannot find it anymore.

What is the difference between `-As 'PS'` vs `-As 'Mdbc.Dictionary'` vs `-As 'BsonDocument'`

When do I want to use Mdbc.Dictionnary instead of a PSObject ? Should I prefer one instead of the other ?

**Comment by nightroman** [comment]
The exact answer depends on some unknowns in your scenarios. In the end you
choose what is better in a particular case.

### Mdbc.Dictionary

In most cases use `Mdbc.Dictionary`. This is the default, so that you do not
have to use `-As` explicitly. It is effective and PowerShell friendly wrapper
of `BsonDocument`. Features:

- good performance
- dot-notation for accessing data "like properties"
- easy to add and remove data or check for existence
- the wrapped `BsonDocument` is still there, if needed

`Mdbc.Dictionary` is not the best for "visualizing" using `Format-*` cmdlets or
further operations with `Select-Object`, `Group-Object`, etc.

### BsonDocument

I would say, do not use it unless other tools expect input as `BsonDocument`.
This type is not PowerShell friendly for using directly.

In particular:

- dot-notation is not supported
- values are returned as `Bson*` types, not usual numbers, strings, etc.
- it is not a dictionary, so it cannot be used as input where a dictionary is expected

### PS (PSCustomObject)

It is a "PowerShell property bag". It is handy for `Format-*` commands
(visualization) and operations with `Select-Object`, `Group-Object`
(further data manipulation).

Price? It is relatively expensive to build, comparing to `Mdbc.Dictionary`.

Also, it is more difficult to add and remove data or check for existence.
(But this is still possible using `$x.PSObject.Properties` members.)

**Comment by avezinaATastus** [comment]
Hi, 
Thanks for the answer. Sorry, yesterday was holiday over here :)

I am trying to add a type to the returned objects to get some custom format in my module (via format.ps1xml).

I do this to add my type :  `$_.PSTypeNames.Insert(0, "My.ServiceManagement.Service")`

When I used `-As PS`, then add my type, my formatting works. But after reading your comment, it might be better that I use Mdbc.Dictionnary.

Here is the problem : My type is correctly added to the PSTypeNames property, but my formatting doesn't apply. After a quick `Get-Member`, I think it is because my document's field aren't exposed directly, unlike the PSCustomObject.

Do you have a trick to "expose" fields property more directly on the mdbc.Dictionnary ?

```powershell
PS C:\Users\avezina\gitrepos\serviceManagement> Get-mdbService | gm           

   TypeName: My.ServiceManagement.Service

Name           MemberType            Definition
----           ----------            ----------
Add            Method                void Add(string key, System.Object value), void IDictionary[string,Object].Add(string key, System.Object value), void ICollection[KeyValuePair[string,Object]].Add(System.Collections.Ge... 
Clear          Method                void Clear(), void ICollection[KeyValuePair[string,Object]].Clear(), void IDictionary.Clear()
Contains       Method                bool Contains(System.Object key), bool ICollection[KeyValuePair[string,Object]].Contains(System.Collections.Generic.KeyValuePair[string,System.Object] item), bool IDictionary.Contains(... 
ContainsKey    Method                bool ContainsKey(string key), bool IDictionary[string,Object].ContainsKey(string key)
CopyTo         Method                void ICollection[KeyValuePair[string,Object]].CopyTo(System.Collections.Generic.KeyValuePair[string,System.Object][] array, int arrayIndex), void ICollection.CopyTo(array array, int in... 
EnsureId       Method                void EnsureId()
Equals         Method                bool Equals(System.Object obj)
GetEnumerator  Method                System.Collections.Generic.IEnumerator[System.Collections.Generic.KeyValuePair[string,System.Object]] GetEnumerator(), System.Collections.Generic.IEnumerator[System.Collections.Generic... 
GetHashCode    Method                int GetHashCode()
GetType        Method                type GetType()
Print          Method                string Print()
Remove         Method                void Remove(System.Object key), bool IDictionary[string,Object].Remove(string key), bool ICollection[KeyValuePair[string,Object]].Remove(System.Collections.Generic.KeyValuePair[string,... 
ToBsonDocument Method                MongoDB.Bson.BsonDocument ToBsonDocument(), MongoDB.Bson.BsonDocument IConvertibleToBsonDocument.ToBsonDocument()
ToString       Method                string ToString()
TryGetValue    Method                bool TryGetValue(string key, [ref] System.Object value), bool IDictionary[string,Object].TryGetValue(string key, [ref] System.Object value)
Item           ParameterizedProperty System.Object Item(string key) {get;set;}, System.Object IDictionary.Item(System.Object key) {get;set;}
Count          Property              int Count {get;}
IsFixedSize    Property              bool IsFixedSize {get;}
IsReadOnly     Property              bool IsReadOnly {get;}
IsSynchronized Property              bool IsSynchronized {get;}
Keys           Property              System.Collections.Generic.ICollection[string] Keys {get;}
SyncRoot       Property              System.Object SyncRoot {get;}
Values         Property              System.Collections.Generic.ICollection[System.Object] Values {get;}


PS C:\Users\avezina\gitrepos\serviceManagement> Get-mdbService -ShowOnly | gm   # My switch -ShowOnly switches to '-As PS'



   TypeName: My.ServiceManagement.Service

Name        MemberType   Definition
----        ----------   ----------
Equals      Method       bool Equals(System.Object obj)
GetHashCode Method       int GetHashCode()
GetType     Method       type GetType()
ToString    Method       string ToString()
Config      NoteProperty System.Management.Automation.PSCustomObject Config=@{ConfigPath=; LogTypeList=}
DependsOn   NoteProperty ArrayList DependsOn=System.Collections.ArrayList
Install     NoteProperty System.Management.Automation.PSCustomObject Install=@{InstallPath=; Version=}
Log         NoteProperty System.Management.Automation.PSCustomObject Log=@{LogPath=; LogTypeList=}
Name        NoteProperty string Name=devicePX
_id         NoteProperty ObjectId _id=5e336a5f56be743e9ce33723
```

**Comment by nightroman** [comment]
I think PS formatting is supposed to work with `PSCustomObject`, not dictionaries, including `Mdbc.Dictionary`.
In other words, in your scenario you should probably use `PSCustomObject`, i.e. `-As PS`. Regardless of its cons.
Like I said the exact answer depends on a scenario.

**Comment by nightroman** [comment]
>I do this to add my type : $_.PSTypeNames.Insert(0, "My.ServiceManagement.Service")

This is an interesting part. As far as I understand, you do it yourself with result objects, right? If you think Mdbc should help in doing this, let me know or open another issue perhaps.

**Comment by avezinaATastus** [comment]
Well, its because I'm trying to format the output with my custom type.

But I just learned that because it is a dictionnary, it will never hit the formatter.

So I really need to use the PSCustomObjects

Thanks again for your help
