### ISSUE TITLE
Inserting an array as a document

### ISSUE THREAD

**Issue by alisaadgs** [nightroman/Mdbc#44]
Hello,

I was trying to insert an array of students as a document in my mongoDB.

Import-Module Mdbc
Connect-Mdbc . vflow students
@{_id = 1; "student_name" =  {"John"; "Sara"; "Ali" }  } | Add-MdbcData

But I got an error in powershell saying: "Add-MdbcData : .NET type System.Management.Automation.ScriptBlock cannot be mapped to a BsonValue"

In mongodb, it was sufficient to write the following command:
db.students.insert( { "student_name": [ "John", "Sara", "Ali" ] } )

How can i apply this correctly using MDBC module?

Thanks in advance.

**Comment by nightroman** [comment]
Instead of `{"John"; "Sara"; "Ali" }` (scriptblock syntax in PS) use `@("John"; "Sara"; "Ali")` (array syntax in PS).

**Comment by alisaadgs** [comment]
Thanks very much, it worked perfectly.
