### ISSUE TITLE
unkown top level operator

### ISSUE THREAD

**Issue by alisaadgs** [nightroman/Mdbc#45]
Hello,

When I try to update a document in my collection, i get this error:

 Update-MdbcData : WriteConcern detected an error 'unknown top level operator:
 $set'. (Response was { "ok" : 1, "code" : 2, "err" : "unknown top level
 operator: $set", "n" : NumberLong(0), "updatedExisting" : false }).
 Update-MdbcData @{_id = 1} @{'$set' = @{value = 100}}
   CategoryInfo          : NotSpecified: (System.Collections.Hashtable:Hashta
   ble) [Update-MdbcData], MongoWriteConcernException
     FullyQualifiedErrorId : Mdbc,Mdbc.Commands.UpdateDataCommand

My script:

Import-Module Mdbc

Connect-Mdbc . db_vflow col_tests

@{_id = 1; value = 42}, @{_id = 2; value = 3.14} | Add-MdbcData
Update-MdbcData @{_id = 1} @{'$set' = @{value = 100}}

Thanks in advance
Ali

**Comment by nightroman** [comment]
Hi @alisaadgs . Your code works for me. What are your Mdbc and MongoDB versions?

**Comment by alisaadgs** [comment]
Hi,

Mdbc version : 5.2.0
MongoDB verision : 4.2.7
Powershell version : 7.0.3

**Comment by alisaadgs** [comment]
Hi again,

I tried adding -update bedore @{'$set' = ...
and it worked for me
so my update command is now :  `Update-MdbcData @{_id = 1} -update @{'$set' = @{value = 100}}`

We can close the issue.
Thanks

**Comment by nightroman** [comment]
Mdbc is rather old, the latest is v6.5.6 (with some breaking changes in 6.0.0). I recommend moving to the latest anyway.
It's good you solved the issue, closing.
