### ISSUE TITLE
How to call database methods such as db.getCollectionInfos()?

### ISSUE THREAD

**Issue by lesterw1** [nightroman/Mdbc#49]
How can I call a database method such as **[db.getCollectionInfos()](https://docs.mongodb.com/manual/reference/method/db.getCollectionInfos/)** using **Invoke-MdbcCommand**?

I need to retrieve the validator settings for a given collection and this is the only way to do so (apparently).  But in general, it would be good to know the correct syntax for calling the MongoDB database methods. An example here and in the help would be great.

If there is no way to invoke a database method, then please add **Invoke-MdbcMethod** to the wish list! Thank you.

**Comment by nightroman** [comment]
Please take a look at the command `Invoke-MdbcCommand`.
It should be exactly what you look for.

Example for your question:

```powershell
Connect-Mdbc . test
Invoke-MdbcCommand '{listCollections: { resource: { db: "test", collection: "" }, actions: [ "listCollections" ] }}'
```

See help for `Invoke-MdbcCommand` and a few examples there.

But Mdbc docs do not provide syntax of MongoDB commands.
There is no need to duplicate this huge amount of information.
See MongoDB http://www.mongodb.org for details.

**Comment by lesterw1** [comment]
I'm not sure I follow how to get from **db.getCollectionInfos()** to **listCollections**.  The above sample only produces the following output:

```
Name                           Value                                                                                                          
----                           -----                                                                                                          
cursor                         {id, ns, firstBatch}                                                                                           
ok                             1                                                                                                              
$clusterTime                   {clusterTime, signature}                                                                                       
operationTime                  6900489732736679937                                                                                            
```

I need to find a way to list the collections with the validators. ```Get-mdbcCollection``` doesn't return this. Any other thoughts?

**Comment by nightroman** [comment]
@lesterw1 I do not really know, too. If I knew I'd tell you right away.
I've just tried to save the result to `$r` and then `$r.cursor.firstBatch` gets my collections. Dig into MongoDB docs for more details.

**Comment by gjh71** [comment]
> How can I call a database method such as **[db.getCollectionInfos()](https://docs.mongodb.com/manual/reference/method/db.getCollectionInfos/)** using **Invoke-MdbcCommand**?
> 
> I need to retrieve the validator settings for a given collection and this is the only way to do so (apparently). But in general, it would be good to know the correct syntax for calling the MongoDB database methods. An example here and in the help would be great.
> 
> If there is no way to invoke a database method, then please add **Invoke-MdbcMethod** to the wish list! Thank you.

I'd say the addition of **Invoke-MdbcMethod** would be rather elegant. Myself I'm looking for the number of connections: 'db.serverStatus().connections'
