### ISSUE TITLE
Unable to use the -collection option with Get-MdbcData

### ISSUE THREAD

**Issue by smaughan** [nightroman/Mdbc#5]
Hello, 

I am unable to use Get-MdbcData -collection: 

PS C:\Windows\system32> Get-MdbcData -as PS -collection cmdb.oasis_detail
Get-MdbcData : Cannot bind parameter 'Collection' to the target. Exception setting "Collection": "Unexpected type of parameter or variable Collection."
At line:1 char:33
+ Get-MdbcData -as PS -collection cmdb.oasis_detail
+                                 ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-MdbcData], ParameterBindingException
    + FullyQualifiedErrorId : ParameterBindingFailed,Mdbc.Commands.GetDataCommand

**Comment by nightroman** [comment]
Is it the only command that you invoke? Then of course this is not enough.

Take a look at `help Get-MdbcData -full`

    -Collection

        Collection object. It is obtained by Connect-Mdbc or from database or
        server objects. If it is not specified then the current variable
        Collection is used.

In other words, `Collection` is not a collection name, it is a collection object.
You should obtains this object at first (i.e. open a collection). For example:

```powershell
    Connect-Mdbc mongodb://... cmdb oasis_detail
```

In particular this command creates the variable `$Collection` (by default, the
name can be specified). This collection now can be used for other commands
explicitly:

```powershell
    Get-MdbcData -Collection $Collection
```

or even implicitly

```powershell
    Get-MdbcData
```

If this answers the question please close the issue.

**Comment by smaughan** [comment]
So if I use * for collection name on the Connect-Mdbc command, how to I
specify which collection to use for the Get-MdbcData command?

[image: Inline image 1]

[image: Inline image 3]


Or which collection will be used by

    Get-MdbcData -Collection $Collection

**Comment by smaughan** [comment]
![capture](https://cloud.githubusercontent.com/assets/12530973/7730235/44ac1a48-fed6-11e4-8b3a-6bbe193fdd70.JPG)

**Comment by nightroman** [comment]
Hmm, why do you use `*` as the collection name?

Anyway, if you explain your task then I will tell you how to solve it.

**Comment by smaughan** [comment]
What I am attempting to do is this (forgive me, I am new at MongoDB.)  It seems that when I connect to the second collection, I lose the values set from the first collection. 




from documents that match a value in collection1, extract several fields

then check for documents in collection2 that match the same value, and extract fields from documents in collection2

then write the record out to a file


$sitelist = "007887","016114","017755"

# Load the driver module
Import-Module Mdbc

# Connect to the oasis_detail collection
Connect-Mdbc mongodb://${username}:${password}@donotpassgo.mo.us.att.com:37017/$databaseName -DatabaseName $databaseName -CollectionName $collectionName1

# Pull information from the oasis_detail collection

ForEach ($site in $sitelist) {

    Set-Variable -Name oasis -value (Get-MdbcData (New-MdbcQuery geolink_reference.site.site_id -EQ $site) -Property att_name) 
    ForEach ($server in $oasis.att_name) {
        
        Set-Variable -Name oasis_data -value (Get-MdbcData -as PS (New-MdbcQuery att_name -EQ $server) -Property client_systems,
            att_name,
            model,
            serial_number,
            production_state,
            geolink_reference)

#  Here, check for documents in a different collection (att_info) where oasis_data.att_name matches
#  Property "General Information.HOSTNAME" and extract data from those documents. Then, write
#  out the output. 

# Connect-Mdbc mongodb://${username}:${password}@donotpassgo.mo.us.att.com:37017/$databaseName -DatabaseName $databaseName -CollectionName $collectionName2

#         Set-Variable -Name attinfo -value (Get-MdbcData -as PS (New-MdbcQuery "General Information.HOSTNAME" -EQ $oasis_data.att_name) -Property -"General Information.HOSTNAME",
#    "COLLECTED DATE",
#   "Operating System.OS_RELEASE",
#    "Operating System.OS_VERSION",
#    "General Information.MANUFACTURER",
#    "General Information.MODEL",
#    "General Information.SERIAL_NUMBER",
#    "General Information.LAST_BOOT",
#    "General Information.DOMAIN" 

       write-host $oasis_data.client_systems.name,
            $oasis_data.att_name,
            $oasis_data.model, 
            $oasis_data.geolink_reference.serial_number,
            $oasis_data.production_state.name,
            $oasis_data.geolink_reference.management_type

            
    }
}

**Comment by smaughan** [comment]
Wow, that formatting is messed up!

**Comment by nightroman** [comment]
Do not worry about "new at MongoDB". And about formatting, I'll fix it. Now I've got to go, give me some time.

**Comment by nightroman** [comment]
At first the explanation of technique for working with several collections:

```powershell

# connect just to the database, the variable $Database is created, as a result
Connect-Mdbc "<connection-details>" "<database-name>"

# get collection 1 and 2 from the database
$collection1 = $Database["<collection1-name>"]
$collection2 = $Database["<collection2-name>"]

# get data (or call other commands) from both collections
$data1 = Get-MdbcData -Collection $collection1 ...
$data2 = Get-MdbcData -Collection $collection2 ...
```

So your code will be (approximately!) something like

```powershell

# As far as we are going to work with several collections, connect to the
# database only. We will get needed collections later using $Database.
Connect-Mdbc mongodb://${username}:${password}@donotpassgo.mo.us.att.com:37017/$databaseName

# Now let's get the oasis_detail collection from the $Database:
$collection1 = $Database['oasis_detail']

ForEach ($site in $sitelist) {
    # Here we use the object $collection1
    $oasis = Get-MdbcData -Collection $collection1 (New-MdbcQuery geolink_reference.site.site_id -EQ $site) -Property att_name

    ForEach ($server in $oasis.att_name) {
        # Here we use the object $collection1 again
        $oasis_data = Get-MdbcData -Collection $collection1 -As PS (New-MdbcQuery att_name -EQ $server) -Property client_systems,
        att_name, model, serial_number, production_state, geolink_reference

        #  Here, check for documents in a different collection (att_info) where oasis_data.att_name matches
        #  Property "General Information.HOSTNAME" and extract data from those documents. Then, write
        #  out the output.

        # Sorry, I do not get what the name of another collection is, set it here yourself please:
        $collectionName2 = ...

        # let's get this collection from the database:
        $collection2 = $Database[$collectionName2]

        # Now use the $collection2 with Get-MdbcData:
        $attinfo = Get-MdbcData -Collection $collection2 -As PS (New-MdbcQuery "General Information.HOSTNAME" -EQ $oasis_data.att_name) -Property ...

        ...
    }
}
```

**Comment by smaughan** [comment]
I think I am almost there, thanks! I have one more issue I cannot figure out.  Is this some kind of syntax error?  What am I doing wrong? 

![capture](https://cloud.githubusercontent.com/assets/12530973/7735772/93b92e02-fefc-11e4-9134-233c895251b2.JPG)

**Comment by smaughan** [comment]
Ah, I got it!  Thanks so much for your help!  You are awesome!

**Comment by smaughan** [comment]
Hi,

We had this working when I last tried it, but today I get some errors.  Do
you know what I am missing?

[image: Inline image 1]

**Comment by nightroman** [comment]
It is difficult to tell without knowing the details. Presumably you use the updated code and deal with a new issue. If it is the issue shown at the picture then I do not understand what wrong is.

**Comment by smaughan** [comment]
It does not seem to be creating the $Database variable, so when I try to
use $Database it fails.


[image: Inline image 2]

**Comment by nightroman** [comment]
You may open another issue. BTW, did you attach another image? I cannot see it.
