### ISSUE TITLE
Selecting field using Get-MdbcData

### ISSUE THREAD

**Issue by kipster521** [nightroman/Mdbc#52]
I would like to select a field (styleType) from a collection and return its values into a file. This is what my code looks like: 
   ``` Get-MdbcData -Collection $MyColl -Project styleType  | Export-MdbcData $Path -Append  ```
The error message I received is: **JSON reader was expecting a value but found 'styleType'.**
Is Project not the correct parameter for selecting fields?

**Comment by nightroman** [comment]
What type is `styleType`? Before digging into the code (I do not remember :)), maybe `Export-MdbcData` is expecting objects but find scalars.

**Comment by kipster521** [comment]
```styleType``` is a String.

**Comment by nightroman** [comment]
You should use a projection expression, something like `"{styleType: 1}"` or `@{styleType=1}`.

```
0> help Get-MdbcData -Parameter Project

-Project
    Specifies the projection expression, i.e. fields to be retrieved. The field _id is always included unless it is explicitly excluded.

    The special value `*` used together with `-As <type>` tells to infer projected fields from the type.

    Otherwise, the argument is either JSON or similar dictionary.
```

See also: https://docs.mongodb.com/manual/tutorial/project-fields-from-query-results/

**Comment by kipster521** [comment]
Below is the updated code that worked. Thanks for your assistance.
```Get-MdbcData -Project @{styleType=1; _id=0} | Export-MdbcData $Path -Append```
