### ISSUE TITLE
Need simple PS script to change mongo user password

### ISSUE THREAD

**Issue by paulepadilla** [nightroman/Mdbc#61]
I have all necessary bits to use mdbc and I need simple PS script to change user's password.

TIA

**Comment by nightroman** [comment]
Mdbc does not have such a command.

Mdbc uses the MongoDB C# driver. If the driver has such a method then we
probably may call it directly from PowerShell. I cannot find such a method. If
you can find it, please let me know and I will help with an example of calling
it.

Then, Mdbc has `Invoke-MdbcCommand` which may invoke MongoDB commands using
input similar to their documented JSON. I cannot find such a command either.
If you can find it, please let me know and I will help to compose
`Invoke-MdbcCommand` input accordingly.

So far I can only find examples of changing user passwords using MongoDB shell.
See https://docs.mongodb.com/manual/reference/method/db.changeUserPassword/

In theory you can call the shell with the required command from PowerShell:

```
mongo <parameters> --eval 'use products; db.changeUserPassword("accountUser", "SOh3TbYhx8ypJPxmt1oOfL")'
```

Maybe this is the only way. The only way I can find at least.

**Comment by paulepadilla** [comment]
Thank you for the quick reply.  Do I need to use "Connect-Mdbc" before using the "invoke-MdbcCommand"?

TIA

**Comment by nightroman** [comment]
Yes, because `Invoke-MdbcCommand` requires a database, either explicitly as the parameter or implicitly as the variable created by `Connect-Mdbc`.

**Comment by paulepadilla** [comment]
Your support is first class

**Comment by nightroman** [comment]
Thank you :)
Could you please tell how exactly you solved the problem? This will help me and others.

**Comment by paulepadilla** [comment]
I havent yet.  I’m on an airplane now, getting ready to take off on 5 hour
flight back home to Florida 😄.  Will try it out and let you know.  Can you
please write the entire script for me so I don’t have to fiddle with it?
Please test of course and I’ll paypal you for your trouble?

**Comment by nightroman** [comment]
Have a nice flight :)

It's not about paypal for my trouble, I am happy to help. I just do not know the exact complete answer yet. You need to do some work and digging, too. Follow my hints, hope they help.

**Comment by paulepadilla** [comment]
I tried the test sample:

` # Load the module
Import-Module Mdbc

# Connect the new collection test.test
Connect-Mdbc . test test -NewCollection

# Add some test data
@{_id=1; value=42}, @{_id=2; value=3.14} | Add-MdbcData

# Get all data as custom objects and show them in a table
Get-MdbcData -As PS | Format-Table -AutoSize | Out-String

# Query a document by _id using a query expression
$data = Get-MdbcData (New-MdbcQuery _id -EQ 1)
$data

# Update the document, set the 'value' to 100
$data._id | Update-MdbcData (New-MdbcUpdate -Set @{value = 100})

# Query the document using a simple _id query
Get-MdbcData $data._id

# Remove the document
$data._id | Remove-MdbcData

# Count remaining documents, 1 is expected
Get-MdbcData -Count 
`
and got this back

` Connect-Mdbc : A timeout occurred after 30000ms selecting a server using CompositeServerSelector{ Selectors = MongoDB.Driver.MongoClient+AreSessionsSupportedServerSelector, LatencyLimitingServerSelector{ AllowedLatencyRange = 00:00:00.0150000 } }. Client 
view of cluster state is { ClusterId : "1", Type : "Unknown", State : "Disconnected", Servers : [{ ServerId: "{ ClusterId : 1, EndPoint : "Unspecified/localhost:27017" }", EndPoint: "Unspecified/localhost:27017", ReasonChanged: "Heartbeat", State: 
"Disconnected", ServerVersion: , TopologyVersion: , Type: "Unknown", HeartbeatException: "MongoDB.Driver.MongoConnectionException: An exception occurred while opening a connection to the server. ---> System.Net.Sockets.SocketException: No connection could be 
made because the target machine actively refused it [::1]:27017
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.<>c.<ConnectAsync>b__314_0(IAsyncResult iar)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MongoDB.Driver.Core.Connections.TcpStreamFactory.<ConnectAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MongoDB.Driver.Core.Connections.TcpStreamFactory.<CreateStreamAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MongoDB.Driver.Core.Connections.BinaryConnection.<OpenHelperAsync>d__51.MoveNext()
   --- End of inner exception stack trace ---
   at MongoDB.Driver.Core.Connections.BinaryConnection.<OpenHelperAsync>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MongoDB.Driver.Core.Servers.ServerMonitor.<InitializeConnectionAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MongoDB.Driver.Core.Servers.ServerMonitor.<HeartbeatAsync>d__34.MoveNext()", LastHeartbeatTimestamp: "2021-07-22T10:41:56.8217441Z", LastUpdateTimestamp: "2021-07-22T10:41:56.8217441Z" }] }.
At line:5 char:1
+ Connect-Mdbc . test test -NewCollection
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-Mdbc], TimeoutException
    + FullyQualifiedErrorId : System.TimeoutException,Mdbc.Commands.ConnectCommand
 
Add-MdbcData : Specify a collection by the parameter or variable Collection.
At line:8 char:44
+ @{_id=1; value=42}, @{_id=2; value=3.14} | Add-MdbcData
+                                            ~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Add-MdbcData], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,Mdbc.Commands.AddDataCommand
 
Get-MdbcData : Specify a collection by the parameter or variable Collection.
At line:11 char:1
+ Get-MdbcData -As PS | Format-Table -AutoSize | Out-String
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-MdbcData], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,Mdbc.Commands.GetDataCommand
 
New-MdbcQuery : The term 'New-MdbcQuery' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:14 char:23
+ $data = Get-MdbcData (New-MdbcQuery _id -EQ 1)
+                       ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (New-MdbcQuery:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
New-MdbcUpdate : The term 'New-MdbcUpdate' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:18 char:30
+ $data._id | Update-MdbcData (New-MdbcUpdate -Set @{value = 100})
+                              ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (New-MdbcUpdate:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
Get-MdbcData : Specify a collection by the parameter or variable Collection.
At line:21 char:1
+ Get-MdbcData $data._id
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-MdbcData], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,Mdbc.Commands.GetDataCommand
 
Remove-MdbcData : Input document cannot be null.
At line:24 char:13
+ $data._id | Remove-MdbcData
+             ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Remove-MdbcData], PSArgumentException
    + FullyQualifiedErrorId : Argument,Mdbc.Commands.RemoveDataCommand
 
Get-MdbcData : Specify a collection by the parameter or variable Collection.
At line:27 char:1
+ Get-MdbcData -Count
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-MdbcData], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,Mdbc.Commands.GetDataCommand
  
`

**Comment by nightroman** [comment]
@paulepadilla The comment is a different issue. It looks like your local MongoDB server is not running.

P.S.
Please open new issues for new issues or questions.
Please try to improve formatting. Use the Preview tab before submitting.
