### ISSUE TITLE
Add-Mdbc Data is not taking a PSObject

### ISSUE THREAD

**Issue by francescasuba** [nightroman/Mdbc#63]
`Import-Module -Name HPEOneView.600

$user = 'SampleUsername'

$pass = ConvertTo-SecureString 'SamplePassword' -AsPlainText -Force

$cred = New-Object System.Management.Automation.PSCredential ($user, $pass)

$hosts = @('sample.host.com', 'sample2.host.come')
foreach($h in $hosts){
    Connect-OVMgmt -Hostname $h -Credential $cred
    $finalResults = Get-OVAlert -Severity Critical -Count 200 #| New-MdbcData -Id {$_.Id}
    Disconnect-OVMgmt -Hostname $h
}

Connect-Mdbc -ConnectionString SampleConnectionString -DatabaseName SampleDBName -CollectionName "SampleTable" 

$Database = Get-MdbcDatabase -Name SampleDBName

$Collection = Get-MdbcCollection -Name "SampleTable" -Database $Database

Add-MdbcData -InputObject $finalResults -Collection $Collection`

I have two OneView hosts, and I want to use the Get-OVAlert command for both of those hosts to pull the critical alerts. I then have to take those alerts ($finalResults) and put it in a MongoDB. For some reason, if I go a GetType() on the variable $finalResults, it reads as an array PSObject. However, the function Add-MdbcData does not read it as a PSObject, it reads it as an HPEOneView.Library.ApplianceConnection. The error reads:

"Add-MdbcData : Cannot convert 'System.Management.Automation.PSCustomObject' to 'BsonDocument'. -- Cannot convert 'HPEOneView.Library.ApplianceConnection' to 'BsonValue'."

**Comment by nightroman** [comment]
What is the error? (You copy/pasted a different text instead of the error)

The similar scenario works for me:

```powershell
Import-Module Mdbc
Connect-Mdbc -NewCollection

$res = Get-Process *chrome* | New-MdbcData -Id {$_.Id} -Property Name, WorkingSet
Add-MdbcData -InputObject $res

Get-MdbcData
```

**Comment by francescasuba** [comment]
Apologies, my comment has been edited

**Comment by nightroman** [comment]
Well, the error tells it all. Mdbc does not know how to make BsonValue from 'HPEOneView.Library.ApplianceConnection'. You have to convert manually. Unfortunately (inevitably) some types are too complex for auto conversion.

**Comment by nightroman** [comment]
You can use the `-Convert` script, something like:

```powershell
... | New-MdbcData -Id {$_.Id} -Convert {
	if ($_ is [HPEOneView.Library.ApplianceConnection]) {
		# convert $_ to some PSCustomObject, Hashtable, etc.
	}
}
```

**Comment by francescasuba** [comment]
`foreach($h in $hosts){
    Connect-OVMgmt -Hostname $h -Credential $cred
    $alerts = Get-OVAlert -Severity Critical -Count 200
    foreach($alert in $alerts){
        New-MdbcData -Id {$alert.Id} -Convert {
            if ($alert.type -eq [HPEOneView.Library.ApplianceConnection]) {
		        # convert $_ to some PSCustomObject, Hashtable, etc. and return it instead of $_
                $finalResults = [pscustomobject]$alert
	        } 
        }
    }
    Disconnect-OVMgmt -Hostname $h
}`

I am getting the error: New-MdbcData : Object reference not set to an instance of an object.

**Comment by francescasuba** [comment]
https://github.com/francescasuba/sample/blob/3b2aeeab80cfd00c55012eaa83e622cc2edcf12d/oneview

I am getting the error: New-MdbcData : Object reference not set to an instance of an object.

**Comment by francescasuba** [comment]
`foreach($alert in $alerts){
        New-MdbcData -InputObject $alert -NewId -Convert {
            if ($alert.type -eq [HPEOneView.Library.ApplianceConnection]) {
		        # convert $_ to some PSCustomObject, Hashtable, etc. and return it instead of $_
                $finalResults = [pscustomobject]$alert
	        }
        }
`

This is working better, but it has split the alerts every three lines instead of just one alert

**Comment by nightroman** [comment]
> I am getting the error: New-MdbcData : Object reference not set to an instance of an object.

because you do not input anything to `New-MdbcData`. OK, do not use it all. I recommend to convert your HPEOneView.Library.ApplianceConnection objects manually to Hashtable and send these tables to Add-MdbcData. This should work. I am closing, it's now PowerShell programming issue, not Mdbc.

**Comment by francescasuba** [comment]
Add-MdbcData : Cannot convert 'HPEOneView.Library.ApplianceConnection' to 'BsonValue'.
At E:\node2\node\Default\http\update-Oneview.ps1:140 char:42
+     $alert | Convert-ObjectToHashTable | Add-MdbcData
+                                          ~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (System.Collections.Hashtable:PSObject) [Add-MdbcData], ArgumentException
    + FullyQualifiedErrorId : BsonValue,Mdbc.Commands.AddDataCommand

@nightroman I understand. Just so you know, I converted the objects to hashtables and still erroring

**Comment by nightroman** [comment]
OK. How do you convert? What is `Convert-ObjectToHashTable`? What properties of your input objects do you want to store?

**Comment by francescasuba** [comment]
Convert-ObjectToHashTable Function: https://kpatnayakuni.com/2019/11/26/powershell-convert-object-properties-into-hashtable/

Propoerties: Severity, Resource, Created, Modified, State, Description

**Comment by nightroman** [comment]
This cmdlet makes shallow conversion. If properties are complex then `Convert-ObjectToHashTable` should be applied to them as well.

What are the types of these properties: Severity, Resource, Created, Modified, State, Description?
Are there other properties?

**Comment by nightroman** [comment]
```powershell
# Assuming Severity, Resource, Created, Modified, State, Description are simple types, try this

$alert | Select-Object Severity, Resource, Created, Modified, State, Description | Add-MdbcData

# But if they are not simple then convert them...
```

**Comment by francescasuba** [comment]
`foreach($alert in $alerts){
    Add-MdbcData -InputObject $alert -Convert {$_ | Convert-ObjectToHashtable} -NewId -Collection $Collection
}`

This actually worked! :) Piped the Convert-ObjectToHashtable function as the -Convert script and it worked like a charm. Thanks for sticking it out!

**Comment by nightroman** [comment]
I am really glad it worked for you. And the way you did this is actually exactly ho it all designed. `-Convert` is called only for pieces that cannot be converted. In this scenario even shallow `Convert-ObjectToHashtable` helps because the whole convert process is recursive (deep). Whew! :)

Like I said, It's all rather about PowerShell and serialization to BSON, not Mdbc as such. Have a nice weekend!
