### ISSUE TITLE
unable to use -options in update-mdbcdata

### ISSUE THREAD

**Issue by swedan333** [nightroman/Mdbc#65]
$arrayFilters = New-Object System.Collections.Generic.List[MongoDB.Driver.ArrayFilterDefinition]
    [MongoDB.Driver.BsonDocumentArrayFilterDefinition]$credentialId = [MongoDB.Bson.BsonDocument]::new('credential.guid', [MongoDB.Bson.BsonDocument]::new('$eq', '8ab9d46a-7af4-46bc-96c3-b98529af1a95'))
    $arrayFilters.Add($credentialId) 

    $mOptions = [MongoDB.Driver.UpdateOptions]::new()
    $mOptions.ArrayFilters = $arrayFilters

    update-mdbcdata -Filter @{} -Collection $colCompany -Update @{'$addToSet' = @{'credential.$[credential].test' = $dataObj}} -Options $mOptions -Result

is there a right way of doing this?

**Comment by nightroman** [comment]
What is the Mdbc version? What is the error? What are trying to do? It looks like you build a filter but use it as `-Options` instead of -`Filter`, it's not clear.

**Comment by nightroman** [comment]
This code runs without errors. But I am not sure it does what you need.

```powershell
$arrayFilters = New-Object System.Collections.Generic.List[MongoDB.Driver.ArrayFilterDefinition]
$filter = [MongoDB.Bson.BsonDocument]::new(@{
	'credential.guid' = @{
		'$eq' = '8ab9d46a-7af4-46bc-96c3-b98529af1a95'
	}
})
[MongoDB.Driver.BsonDocumentArrayFilterDefinition[object]]$credentialId = $filter
$arrayFilters.Add($credentialId)

$mOptions = [MongoDB.Driver.UpdateOptions]::new()
$mOptions.ArrayFilters = $arrayFilters

Update-MdbcData -Filter @{} -Collection $colCompany -Update @{'$addToSet' = @{'credential.$[credential].test' = $dataObj}} -Options $mOptions -Result
```

**Comment by swedan333** [comment]
Hi, and thanks for the quick response!
I'm running Mdbc version 6.5.10 and I am trying to update sub arrays using Arrayfilters, although the code ran without errors it still did not update the record.

**Comment by swedan333** [comment]
Solved!
Was the -filter as you suggested, thought I could update multiple.
thanks for the proper arrayFilters implementation, maybe this should be documented..

**Comment by nightroman** [comment]
I am glad it's solved!

> thanks for the proper arrayFilters implementation, maybe this should be documented..

I do not really know how and what to document in this case. It's just some expected (!) quirks of PowerShell on translating from C#.
