### ISSUE TITLE
Simple authentication supported?

### ISSUE THREAD

**Issue by mdewall** [nightroman/Mdbc#7]
Hi - I looked through the code and Get-Help examples and doesn't appear that simple username/password authentication can be specified.  I also tried via powershell to update the global Server.Settings.Credentials object but it threw an exception that the variables were "frozen".

Before I bring down the code and attempt to add authentication, is it already supported and I'm just missing it?

Thanks!

Matt

**Comment by nightroman** [comment]
Hi Matt,

Honestly, I have no idea how authentication API works. I use MongoDB mostly as a local DB for logs and etc. and it is not needed. Even if I try to implement something I do not know how to test this (and do not really want to know at this point, it's not my area or need in the near future). So if you can bring your code that works please go ahead.

**Comment by nightroman** [comment]
Before you do this please let me know what you are going to do, perhaps I will have some thoughts.

**Comment by mdewall** [comment]
Hi Roman,

Thanks for getting back to me so quickly.  Turns out it was a combination
of things - but it already works and no code changes necessary.  :)

Well...  Maybe a bug fix and an update of the Get-Help docs for the
Conenct-Mdbc - just to show that usernames/passwords are indeed supported.

The Connect-Mdbc can take a connection string (which the user can specify
username:password in as well as the database.)

Connect-Mdbc -ConnectionString "mongodb://
myaccount:mypass@remotehost.example.com/mydatabase"

This was failing for me and I didn't see anything in the scripts suggesting
this would work, so I assumed it wasn't supported.

Turns out my password had an '@' in it, which confused the parser because
there is supposed to be an @servername within the connection string as
well.  Once I changed my pw to not include the @ symbol, it worked without
any issues.

I'm all set - these powershell scripts are great - thank you for your work
on this!

Matt

**Comment by mdewall** [comment]
The full string to connect needs to include the db and the collection:

Connect-Mdbc -ConnectionString "mongodb://myaccount:mypass@remotehost.example.com/mydatabase" -DatabaseName "mydb" -CollectionName "mycollection"

**Comment by nightroman** [comment]
It is already mentioned in help Connect-Mdbc (use `-Full` or `-Parameter ConnectionString`):

````
-ConnectionString
    Connection string (see driver manuals for details):
    mongodb://[username:password@]hostname[:port][/[database][?options]]

    "." is used for the default driver connection.

    Example:
    mongodb://localhost:27017
````

I will add a suggested example "mongodb://myaccount:mypass@remotehost.example.com/mydatabase".
