### ISSUE TITLE
Getting an error while calling Get-MdbcData using PowerShell on Windows 10

### ISSUE THREAD

**Issue by rezongit** [nightroman/Mdbc#70]
Hi nightroman.

I have been trying to enumerate a simple collection using the Mdbc module.  It looks like I connect to the server as I can get the setting for the Database (test) as well as the Collection I am interested in.  However, when I try to get data from the collection, I get an error.  Kindly advise.

Thanks

PS> Connect-Mdbc -ConnectionString "mongodb://myuser:mypassword@192.168.2.4:27017" -DatabaseName "test"

PS> $db_name = Get-MdbcDatabase -Name "test"
PS> $coll_name = Get-MdbcCollection -Database $db_name -Name "mycollection"

PS> Get-MdbcData -Collection $coll_name
Get-MdbcData : Unable to authenticate using sasl protocol mechanism SCRAM-SHA-1.
At line:1 char:1
+ Get-MdbcData -Collection $coll_name
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-MdbcData], MongoAuthenticationException
    + FullyQualifiedErrorId : Mdbc,Mdbc.Commands.GetDataCommand

**Comment by rezongit** [comment]
mongo (db version v4.4.14) is running on an Ubuntu 16.04.7 LTS.

**Comment by nightroman** [comment]
To be honest, I have no idea. Can you play with the shell and get the data their? The issue may have nothing to do with Mdbc.
A side note: Mdbc is being developed with more recent MongoDB, next major version. The currently used version is 5.0.2.

**Comment by nightroman** [comment]
Please take a look at https://mongodb.github.io/mongo-csharp-driver/2.16/reference/driver/authentication/
and specific notes about MongoDB 4.0 that you use (Mdbc is being developed and tested with 5.x)

> When connecting to a MongoDB 4.0 server without specifying an authentication mechanism, the driver will negotiate with the server to determine whether SCRAM-SHA-1 or SCRAM-SHA-256 is the appropriate mechanism.
...

**Comment by nightroman** [comment]
In the meantime, I've just released Mdbc v6.6.1 with the updated C# driver 2.16.1. Just in case.

**Comment by rezongit** [comment]
> In the meantime, I've just released Mdbc v6.6.1 with the updated C# driver 2.16.1. Just in case.

Great.  I'll probably end up upgrading both the os and the Mdbc.

**Comment by nightroman** [comment]
I do not think I have anything to add or help in any way in this case. So I would rather close the issue.

**Comment by rezongit** [comment]
> I do not think I have anything to add or help in any way in this case. So I would rather close the issue.

Sure.
