### ISSUE TITLE
Unable to get collection 

### ISSUE THREAD

**Issue by Azizalorabi** [nightroman/Mdbc#71]
Hi nightroman 
Thank you very much for this useful tool.
I don't think this is an issue , maybe I dont know yet hoe to use Mdbc.
I am using Mac M1 visual studio > Powershell core.
When I try to connect to MongoDB I just use the following:
Import-Module Mdbc
Connect-Mdbc -ConnectionString mongodb://127.0.0.1:27017
Get-MdbcDatabase

And I can see the databases but if I want to see the collection inside a database I got nothing no error (IP_LOOKUP is the name of the collection):
Get-MdbcCollection 
No result no error

Get-MdbcCollection -Name IP_LOOKUP 
--- this is the result:
CollectionNamespace : test.IP_LOOKUP
Database            : MongoDB.Driver.MongoDatabaseImpl
DocumentSerializer  : MongoDB.Bson.Serialization.Serializers.BsonDocumentSerializer
Indexes             : MongoDB.Driver.MongoCollectionImpl`1+MongoIndexManager[MongoDB.Bson.BsonDocument]
Settings            : AssignIdOnInsert=True;GuidRepresentation=Standard;ReadConcern={ };ReadEncoding=null;ReadPreference={ Mode : Primary 
                      };WriteConcern={ };WriteEncoding=null

But makes no sense to me.
I will try later to insert data inside the collection but I can't get it yet :)

**Comment by nightroman** [comment]
If you need `Get-MdbcCollection` to return collections you should either specify the database or use `Connect-Mdbc` with a database name specified as the parameter.

**Comment by Azizalorabi** [comment]
I tried  (DarknessEye is the name of the DB): 
Import-Module Mdbc
Connect-Mdbc -ConnectionString mongodb://127.0.0.1:27017
Get-MdbcCollection DarknessEye

Result shows :
CollectionNamespace : test.DarknessEye
Database            : MongoDB.Driver.MongoDatabaseImpl
DocumentSerializer  : MongoDB.Bson.Serialization.Serializers.BsonDocumentSerializer
Indexes             : MongoDB.Driver.MongoCollectionImpl`1+MongoIndexManager[MongoDB.Bson.BsonDocument]
Settings            : AssignIdOnInsert=True;GuidRepresentation=Standard;ReadConcern={ };ReadEncoding=null;ReadPreference={ Mode : Primary 
                      };WriteConcern={ };WriteEncoding=null

**Comment by nightroman** [comment]
Have you taken a look at the help? E.g. `help Connect-Mdbc -full` etc.
You should use a command like this, to *connect to a database*:

```powershell
Connect-Mdbc -ConnectionString mongodb://127.0.0.1:27017 -DatabaseName DarknessEye
```

**Comment by Azizalorabi** [comment]
Yes I have and I am sorry if my question is just a basic question.
I used this command 
`Connect-Mdbc -ConnectionString mongodb://127.0.0.1:27017 -DatabaseName DarknessEye`

Result shows nothing again and this is why I am struggling.
Thanks again.

**Comment by nightroman** [comment]
This command is not supposed to show anything.
Can you get the complete sequence of commands and expected/actual results for each?

**Comment by Azizalorabi** [comment]
Yes It worked out! 
Now It makes sense to me.
Can you keep the issue open please until I can insert documents? and get back to you if there is any issue :)
I will use help New-MdbcData -Full , I promise :)

**Comment by Azizalorabi** [comment]
This works perfectly
Thank you!

**Comment by nightroman** [comment]
You are very welcome! I am closing this one. Feel free to open another issue.
