### ISSUE TITLE
Some properties are missing for registered types

### ISSUE THREAD

**Issue by codaamok** [nightroman/Mdbc#74]
Firstly, love this. Thank you. I am learning mongodb and being able to learn it with PowerShell helps me so much.

During my learning experience I uncovered Mdbc can't serialise all types, I must use `Register-MdbcClassMap`. Which is fine. As an example, I'm trying to run:

```powershell
get-item .\Downloads\mongodb-windows-x86_64-6.0.3-signed.msi | Add-MdbcData
```

I needed to register all of the following types in order to add the data:

```powershell
Register-MdbcClassMap -Type ([System.IO.DirectoryInfo])
Register-MdbcClassMap -Type ([System.Diagnostics.FileVersionInfo])
Register-MdbcClassMap -Type ([System.Management.Automation.ProviderInfo])
Register-MdbcClassMap -Type ([System.Management.Automation.PSDriveInfo])
```

After this, I was able to successfully add my System.IO.FileInfo object as data to my mongodb collection 🎉 

When looking at the data in the collection, some properties are missing, for example see below screenshot. Is there anything I can do to ensure all properties from other types/objects are added? I'll likely be throwing in Pester data in collections once I get comfortable with how to use. 

![image](https://user-images.githubusercontent.com/6683266/209334681-2bd8084c-0b01-4128-8559-5640528d56c9.png)

**Comment by nightroman** [comment]
I think not every type may be stored/restored as we want or expect. Some types were just not designed for this.

E.g. for `PSDriveInfo` ILSpy shows that `MaximumSize` and `DisplayRoot` are read only. Only PS may set these properties when PS creates these objects. In other words, `PSDriveInfo` was designed for use in PS and creation by PS.

```
public long? MaximumSize { get; internal set; }

public string DisplayRoot
{
	get
	{
		return displayRoot;
	}
	internal set
	{
		displayRoot = value;
	}
}
```

**Comment by nightroman** [comment]
In theory, instead of using `Register-MdbcClassMap` which plugs-in some trivial, default, not designed for special cases serializer, you may register your custom. Using some lower level code. See the C# driver manuals.

But with `PSDriveInfo` you might hit some wall, too. The type is not necessarily designed for what we need.

**Comment by nightroman** [comment]
Class mapping is the advanced C# driver topic (and I'm not exactly an expert).
But in your particular case values might be not "missing" but actual nulls.
Can you check on your side?

For example, this script

```powershell
Set-StrictMode -Version 3

$r = Get-PSDrive C
$r | Format-List * | Out-String

$null -eq $r.MaximumSize
$null -eq $r.DisplayRoot
```

shows that your properties may be nulls.

**Comment by codaamok** [comment]
I'm mostly looking at the Name property more than anything.

```powershell
PS C:\Users\WDAGUtilityAccount> $null -eq (get-item .\Downloads\mongodb-windows-x86_64-6.0.3-signed.msi).psdrive.name
False
PS C:\Users\WDAGUtilityAccount> $null -eq (get-psdrive 'c').name
False
```

Just seems like a regular string?

**Comment by nightroman** [comment]
Well, this is a question to the C# driver class map makers then :) I do not know why `Name` is not saved.
`Name` only has `get`, maybe they do not consider such properties suitable for saving.
Other saved properties have at least `internal set`.

**Comment by nightroman** [comment]
I would not call this issue surprising though. We cannot expect than any type is suitable for mapping and that the default mapping is what we want.

**Comment by nightroman** [comment]
Also, keep in mind that mapping is designed for two way serialization, to BSON first and then recreating from BSON. A property with `get` only is "presumably calculated", so "there is no need to store it".

**Comment by nightroman** [comment]
If you still want to go this route, then you need a custom mapping, read the C# driver manuals.

e.g. this map

```powershell
Register-MdbcClassMap -Type ([System.Management.Automation.PSDriveInfo]) -Init {
	$null = $_.MapProperty('Name')
	$null = $_.MapProperty('Root')
}
```

will results in `Name` and `Root` saved.

**Comment by codaamok** [comment]
I appreciate your insight! Thank you 😄

**Comment by nightroman** [comment]
I think this might work for you:

```powershell
Register-MdbcClassMap -Type ([System.Management.Automation.PSDriveInfo]) -Init {
	$_.AutoMap()
	$null = $_.MapProperty('Name')
}
```

**Comment by nightroman** [comment]
I think I will add this use case to tests, it's useful, thank you for the question.

**Comment by nightroman** [comment]
Here it is
https://github.com/nightroman/Mdbc/blob/a367f5791ec4ee55ea30bf7dee0ca8cc1c707b1f/Tests/Classes.test.ps1#L346-L361
