### ISSUE TITLE
Provide feedback to the user if database or collection does not exist

### ISSUE THREAD

**Issue by codaamok** [nightroman/Mdbc#75]
While using `Connect-Mdbc`, there does not seem to be any safeguard in-place if a database does not exist. Equally, I do not see something telling me whether the database or collection exists or not.

For example:

```powershell
Connect-Mdbc -ConnectionString '.' -DatabaseName 'idonotexist' -CollectionName 'idonotexisteither'
```

This gives me a `$Database`, `$Client`, and `$Collection` variable. I don't see any properties telling me database/collection doesn't exist (if there is, please do correct me!)

If I add data to the database which doesn't exist, it creates the database:

```powershell
@{l = $true} | Add-MdbcData
```

Personally, I would expect:

- some sort of null object or property for the `$Database`, `$Client`, or `$Collection` variable to indicates the database does not exist
- or (preferably), an exception thrown when using `Connect-Mdbc` and telling the user a database or collection if they don't exist
- a cmdlet should ideally be available to create a new database, and not for `Connect-Mdbc` to do this automatically

I see cmdlets exist for removing databases and collections, which is nice.

This is just some feedback from as a new user to both mongodb and your module. However, no doubt this decision crossed your mine and I'm sure there's a philosophy here I'm missing because I literally have zero experience with any kind of database management, let alone working with one in code.

As an aside, and more as an off-topic discussion from this issue / feature request, I see a parameter named `-Result` used where typically `-PassThru` is the popular name for a parameter that behaves like this. I guess this might be both the beauty and pain of PowerShell; there are no rules! One thought I had away from my desk thinking about your module is that some conventions, e.g. the name of `-Result`, deviates from how Microsoft write PowerShell cmdlets However, I certainly don't advocate that Microsoft are the best role models in all of their PowerShell solutions. They forget their own standards in their own products (this is likely a by-product of being a conglomerate). Therefore I don't believe it's fair to say you should do what Microsoft do, but again, as some feedback from me as a new user of Mdbc, who is also OK with PowerShell, Mdbc wasn't quite "pick up and go" for me. 

I know the answer is "open source" and to JFDI myself, but my skills with c# are poor so the best I have is my moaning 😆 

Again, I love this, because it means I can crack on with my project without needing to write _more_ code just to interact with Mongodb. You have saved me lots of time.

**Comment by nightroman** [comment]
@codaamok Quite a topic! :)

Welcome to MongoDB. By its design, you may specify missing databases and collections. They are created on the fly, materialized, as soon as you invoke appropriate commands (like adding data). This may look unusual. And this may lead to some mistakes and confusions, yes. But in many cases it's a useful feature. It is possible because MongoDB collections have no schema, hence there is no need to pre-create something (and hence no need for collections to pre-exist).

**Comment by nightroman** [comment]
`-PassThru` is a popular name. Maybe. I somewhat do not like it for a few reasons. It's not proper English, too. It's just a questionable PS team choice and an author preference, that's it. I do not use `-PassThru` in my own products.
