### ISSUE TITLE
Microsoft.Extensions.Logging.Abstractions macOS arm64

### ISSUE THREAD

**Issue by justcain-ok** [nightroman/Mdbc#79]
Issue:
Connect-Mdbc: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9723829ddaa61'. Could not find or load a specific file. (0x80131621)

I get this behavior in VSCODE only, any suggestions?

**Comment by justcain-ok** [comment]
It seems to be the extension in vs code that trips this up.

**Comment by nightroman** [comment]
I am closing this. It's very unlikely unfortunately that we'll have any progress.
