### ISSUE TITLE
PSGallery

### ISSUE THREAD

**Issue by OverlyExcessive** [nightroman/Mdbc#8]
Hello,

Loving this module! However it would be a nice addition if you would also upload it to PowerShell Gallery. PowerShell Gallery is one of the default Package Management repositories that ship with Windows 10 so then this module could be easily installed by using the `Install-Package` cmdlet.

**Comment by nightroman** [comment]
Hello, why did you close it?

**Comment by OverlyExcessive** [comment]
Seems like you can use `Install-Module` with the `-NuGetPackadeId` just as well to install it. You might want to add this to the installation instructions as it is one of the easiest ways to install your module IMHO 👍 .

**Comment by nightroman** [comment]
I do not see the switch `-NuGetPackadeId` of `Install-Module`.

**Comment by OverlyExcessive** [comment]
Very strange I can't seem to find anything on the cmdlet documentation on TechNet but when writing `Get-Help Install-Module -Full` I get the following output:

```
    Install-Module -NuGetPackageId <string> [-PackageVersion <string>] [-NugetSource <string>] [-PreRelease] [-PreReleaseTag
     <string>] [-Destination <string>] [-ModuleHash <string>] [-Global] [-DoNotImport] [-AddToProfile] [-Update] [-Directory
    Url <string>] [-PersistEnvironment] [-InstallWithModuleName <string>] [-DoNotPostInstall] [-PostInstallHook <string>] [-
    Force] [-Startup]  [<CommonParameters>]
```

_Running PowerShell 5.1 rev 206._

**Comment by avishnyakov** [comment]
Same-same, what's the solution to install this package from the power shell gallery or other sources?

**Comment by nightroman** [comment]
I will push the module to PSGallery when I have some time.
