### ISSUE TITLE
psm1 / Manifest please

### ISSUE THREAD

**Issue by manuel-sperrle** [nightroman/Mdbc#80]
Hi nightroman,

could you please add a manifest / psm1 in order to have the module autoloading if needed?

Would be great.

Thx in advance
Regards,
Manu

**Comment by nightroman** [comment]
I do not want to join discord. Try to rephrase this :) I know that it is "recommended" to list the provided commands in the manifest but I never really seen / understood why. Are you asking to list the module commands in the manifest?

**Comment by nightroman** [comment]
NB Autoloading may not work right away. The initial explicit loading (or maybe even a few) is needed. Autoloading is some PS hidden not well documented magic.

**Comment by manuel-sperrle** [comment]
thx the reply again 
y basically just listing the "Exports": Commands/Cmdlets/Functions inside the psm1 should do - to my believes

there is also a little handy function to do this:
https://learn.microsoft.com/de-de/powershell/module/microsoft.powershell.core/new-modulemanifest

**Comment by nightroman** [comment]
All right, I do not mind to list cmdlets in the manifest, say, "by the book". Fingers crossed, maybe this helps, cannot promise or expect anything though.

**Comment by manuel-sperrle** [comment]
thank you in advance allready - keeping all fingers crossed 
Thx a lot the invested work. (in general)

**Comment by nightroman** [comment]
v6.6.5
Please let me know if this helped (but I close anyway).

**Comment by manuel-sperrle** [comment]
y totally fine now :) - thanks a lot
hint: you may want to remove the import-module in your example aswell - its not needed anymore

**Comment by nightroman** [comment]
I believe the explicit `Import-Module` is still needed for the very first use (like trying the example).

Thank you for reporting, I've learned something new and useful to know.

**Comment by manuel-sperrle** [comment]
Thank you for listening and instant fixing :)

Try out in a silent minute - the explicit Import should not be needed anymore
