### ISSUE TITLE
Regex javascript notation in find command

### ISSUE THREAD

**Issue by ThierryRassat** [nightroman/Mdbc#81]
I try to use regex to find documents in MongoDb
-> https://www.mongodb.com/docs/manual/reference/operator/query/regex/
This notation document @{ '$regex' = 'MailKit*'} is ok
But when I use this notation /Mailkit*/ in my command I have no result 
It's a problem with `$in` because it's not possible to use $regex

**Comment by nightroman** [comment]
What is the full command and sample data? What do you expect to get as the result of this command?

**Comment by nightroman** [comment]
Perhaps something is not quite right with your JSON expression. It's difficult to tell without seeing it.

Please also note that you may use PowerShell `[regex]` with "usual" hashtable expressions, see this demo how-to:
https://github.com/nightroman/Mdbc/blob/805dc6952f069d9a05813e3b5e259a2e19ac7306/Tests/HowTo.test.ps1#L44-L67

**Comment by ThierryRassat** [comment]
Yes, thank you very mutch.
it's ok now. You give the solution with Powershell [regex]
