### ISSUE TITLE
Trying to query using $nin and $regex

### ISSUE THREAD

**Issue by yvesgermain** [nightroman/Mdbc#83]
I'm trying to do a query where I don't want any IdentityReference that starts with either the string "Domain\" or "AUTORITE NT\".  This is what I tried.  How should this query be structured?
Get-mdbcdata -Filter @{ "IdentityReference" = @{'$nin' = @( @{'$regex' = 'Domain\\'}, @{'$regex' = 'AUTORITE NT\\'} )} }

**Comment by yvesgermain** [comment]
The error message is :Get-MdbcData: Command find failed: cannot nest $ under $in.

**Comment by nightroman** [comment]
I think this is error is expected -- https://www.mongodb.com/docs/manual/reference/operator/query/in/#use-the--in-operator-with-a-regular-expression

> You cannot use `$regex` operator expressions inside an `$in`.

Try to recompose the expression using something like ~ not match regex pattern `Domain\\|AUTORITE NT\\`.

**Comment by yvesgermain** [comment]
This worked: Get-MdbcData -Filter @{ "Server" = "GPO";  '$nor' = @(@{ "IdentityReference" = @{'$regex' = '^Domain\\'}}, @{"IdentityReference" = @{'$regex' = '^AUTORITE NT\\'}})}
