### ISSUE TITLE
Update-MdbcData with options

### ISSUE THREAD

**Issue by projectje** [nightroman/Mdbc#85]
Can i run the Update-MdbcData command with options ?  For example

```
$options = @{
            'upsert' = $true
        }
```

and then

`Update-MdbcData -Filter $filter -Update $update -Options $options`?

update: ah wait it should be IsUpsert i think

**Comment by nightroman** [comment]
Yes, it's `IsUpsert`, see
https://mongodb.github.io/mongo-csharp-driver/2.5/apidocs/html/T_MongoDB_Driver_UpdateOptions.htm
